"""Tests for Phase 8 scientific validation (CAPE, IWV, temporal, readiness).

Reference values come from **MetPy**, an independent published implementation,
and from closed-form analytic identities. Nothing here is generated by the code
under test. Where MetPy is unavailable the tests assert the honest
``no_reference_available`` outcome instead of a pass.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Sequence

import numpy as np
import pytest

from app.grid import FRAME_MINUTES, GridSpec
from app.ingestion.base import ObservationCube
from app.ingestion.realtime import validation as V
from app.ingestion.realtime.temporal import (
    DATA_CLASSES,
    assess_temporal_feasibility,
    cadence_matches_contract,
    longest_contiguous_run,
)
from app.physics import GRAVITY, parcel_ascent
from app.training.gate import (
    OBSERVATIONAL,
    PRODUCTION,
    SYNTHETIC_DEMO,
    SYNTHETIC_EVAL,
    EvaluationBlocked,
    TrainingBlocked,
    describe_dataset,
    enforce_evaluation_gate,
    enforce_training_gate,
    verify_provenance,
)

BASE = dt.datetime(2019, 7, 1, tzinfo=dt.timezone.utc)


def _times_30min(n: int = 6) -> list[str]:
    return [(BASE + dt.timedelta(minutes=FRAME_MINUTES * i)).isoformat() for i in range(n)]


def _times_cadence(n: int, minutes: int) -> list[str]:
    return [(BASE + dt.timedelta(minutes=minutes * i)).isoformat() for i in range(n)]


# --------------------------------------------------------------------------- #
# module surface
# --------------------------------------------------------------------------- #
class TestPublicSurface:
    def test_every_export_resolves(self) -> None:
        missing = [name for name in V.__all__ if not hasattr(V, name)]
        assert missing == []

    def test_metpy_available_returns_a_real_bool(self) -> None:
        # Guards the specific regression where the success-path `return True`
        # was missing, making the predicate fall through to None (falsy).
        result = V.metpy_available()
        assert isinstance(result, bool)
        assert result is (V._metpy()[0] is not None)

    def test_lazy_status_constants_resolve(self) -> None:
        assert V.CAPE_VALIDATION_STATUS in (V.PASS, V.FAIL, V.NO_REFERENCE)
        assert V.IWV_VALIDATION_STATUS in (V.PASS, V.FAIL, V.NO_REFERENCE)

    def test_unknown_attribute_raises(self) -> None:
        with pytest.raises(AttributeError):
            V.definitely_not_a_symbol  # noqa: B018

    def test_every_profile_declares_its_provenance(self) -> None:
        for profile in V.REFERENCE_PROFILES:
            assert profile.source.strip()
            assert profile.description.strip()
            assert len(profile.pressure_hpa) == len(profile.temperature_k)
            assert len(profile.pressure_hpa) == len(profile.dewpoint_k)
            assert len(profile.pressure_hpa) >= 3



# --------------------------------------------------------------------------- #
# CAPE: stable / unstable behaviour against an independent oracle
# --------------------------------------------------------------------------- #
def _cape_of(profile: V.ReferenceSounding) -> float:
    return float(
        parcel_ascent(
            np.asarray(profile.pressure_hpa),
            np.asarray(profile.temperature_k),
            profile.specific_humidity_kgkg,
        )["cape"]
    )


class TestCapeAgainstIndependentReference:
    def test_stable_profiles_have_exactly_zero_cape(self) -> None:
        """The regression this phase exists to prevent.

        A saturated parcel must cool as it rises. A reversed sign in that
        integration made stable profiles report ~2810 J kg-1.
        """
        stable = [p for p in V.REFERENCE_PROFILES if p.expect_stable]
        assert len(stable) >= 3
        for profile in stable:
            assert _cape_of(profile) <= 5.0, f"{profile.name} reported {_cape_of(profile)}"

    def test_rising_parcel_always_cools(self) -> None:
        """A parcel lifted through the atmosphere must never warm."""
        for profile in V.REFERENCE_PROFILES:
            parcel = parcel_ascent(
                np.asarray(profile.pressure_hpa),
                np.asarray(profile.temperature_k),
                profile.specific_humidity_kgkg,
            )["parcel_temperature_k"]
            assert np.all(np.diff(parcel) <= 1e-9), (
                f"{profile.name}: parcel warmed with height: {parcel}"
            )

    def test_unstable_profiles_have_large_positive_cape(self) -> None:
        unstable = [p for p in V.REFERENCE_PROFILES if not p.expect_stable]
        assert len(unstable) >= 2
        for profile in unstable:
            cape = _cape_of(profile)
            assert cape > 1000.0, f"{profile.name} reported only {cape} J kg-1"

    def test_stable_cape_is_always_below_unstable_cape(self) -> None:
        stable = min(_cape_of(p) for p in V.REFERENCE_PROFILES if p.expect_stable)
        unstable = max(_cape_of(p) for p in V.REFERENCE_PROFILES if not p.expect_stable)
        assert stable < unstable

    def test_agrees_with_metpy_when_available(self) -> None:
        if not V.metpy_available():
            pytest.skip("MetPy is not installed; no independent reference available")
        for profile in V.REFERENCE_PROFILES:
            check = V.check_cape(profile)
            if profile.expect_stable:
                assert check.status == V.PASS, f"{profile.name}: {check.detail}"
                assert check.reference == 0.0
            else:
                assert check.reference is not None
                assert check.status == V.PASS, f"{profile.name}: {check.detail}"
                relative = abs(check.computed - check.reference) / check.reference
                assert relative <= V.CAPE_REL_TOLERANCE

    def test_report_passes_and_reports_realised_error(self) -> None:
        report = V.run_cape_validation()
        assert report.n_fail == 0, [c.detail for c in report.checks if c.status == V.FAIL]
        assert report.validated is True
        assert report.status == V.PASS
        # Screening-grade accuracy must be visible, not hidden behind pass/fail.
        assert report.max_relative_error is not None
        assert report.max_relative_error <= V.CAPE_REL_TOLERANCE

    def test_report_serialises(self) -> None:
        payload = V.run_cape_validation().to_dict()
        assert payload["feature"] == "cape"
        assert len(payload["checks"]) == len(V.REFERENCE_PROFILES)
        for check in payload["checks"]:
            assert {"name", "computed", "reference", "status", "reference_source"} <= set(check)


# --------------------------------------------------------------------------- #
# CAPE: failure paths and the missing-oracle case
# --------------------------------------------------------------------------- #
class TestCapeFailurePaths:
    def test_stable_profile_with_injected_instability_fails(self) -> None:
        """A deliberately unstable profile must NOT pass the zero-CAPE check."""
        bad = V.ReferenceSounding(
            name="deliberately_unstable_but_marked_stable",
            description="Intentional mismatch: unstable values, stable expectation.",
            source="constructed for this negative test",
            pressure_hpa=(1000.0, 925.0, 850.0, 700.0, 500.0, 400.0, 300.0),
            temperature_k=(303.0, 297.0, 290.0, 280.0, 262.0, 240.0, 225.0),
            dewpoint_k=(300.0, 293.0, 284.0, 271.0, 250.0, 228.0, 210.0),
            expect_stable=True,
            expected_cape=0.0,
        )
        check = V.check_cape(bad)
        assert check.status == V.FAIL
        assert check.computed > 1000.0

    def test_missing_metpy_yields_no_reference_not_pass(self, monkeypatch) -> None:
        monkeypatch.setattr(V, "_metpy", lambda: (None, None))
        assert V.reference_cape_j_per_kg(
            (1000, 850, 700), (300, 285, 270), (290, 275, 260)
        ) is None
        profile = next(p for p in V.REFERENCE_PROFILES if not p.expect_stable)
        check = V.check_cape(profile)
        assert check.status == V.NO_REFERENCE
        assert check.reference is None
        assert "not importable" in check.reference_source

    def test_stable_profiles_still_validate_without_metpy(self, monkeypatch) -> None:
        """Analytic identities do not depend on the oracle being installed."""
        monkeypatch.setattr(V, "_metpy", lambda: (None, None))
        for profile in V.REFERENCE_PROFILES:
            if profile.expect_stable:
                assert V.check_cape(profile).status == V.PASS

    def test_run_cape_validation_honours_a_replaced_profile_set(
        self, monkeypatch
    ) -> None:
        """``run_cape_validation`` must read the module global, not a stale copy.

        Without this, every check would still run against the real profiles and a
        run with no oracle installed would be reported as validated.
        """
        monkeypatch.setattr(V, "_metpy", lambda: (None, None))
        monkeypatch.setattr(
            V, "REFERENCE_PROFILES",
            tuple(p for p in V.REFERENCE_PROFILES if not p.expect_stable),
        )
        report = V.run_cape_validation()
        assert len(report.checks) == len(V.REFERENCE_PROFILES)
        assert report.n_no_reference == len(report.checks)
        assert report.n_pass == 0
        assert report.n_fail == 0
        assert report.validated is False
        assert report.status == V.NO_REFERENCE
        assert report.reference_implementation is None

    def test_empty_report_is_not_validated(self) -> None:
        report = V.ValidationReport("cape", (), None)
        assert report.validated is False
        assert report.status == V.NO_REFERENCE
        assert report.max_relative_error is None

    def test_failing_check_forces_report_failure(self) -> None:
        check = V.CapeCheck("x", computed=999.0, reference=0.0,
                            reference_source="synthetic", status=V.FAIL)
        report = V.ValidationReport("cape", (check,), None)
        assert report.status == V.FAIL
        assert report.validated is False

    def test_input_validation_rejects_malformed_profiles(self) -> None:
        with pytest.raises(ValueError):
            parcel_ascent([1000.0, 900.0], [300.0, 290.0], [0.01, 0.01])
        with pytest.raises(ValueError):
            parcel_ascent([1000.0, 900.0, 800.0], [300.0, 290.0], [0.01, 0.01, 0.005])



# --------------------------------------------------------------------------- #
# IWV: units, ordering, missing levels and boundaries
# --------------------------------------------------------------------------- #
def _iwv(levels: np.ndarray, q: np.ndarray) -> float:
    from app.ingestion.realtime.imdaa_netcdf import derive_iwv

    return float(np.asarray(derive_iwv(levels, q)).squeeze())


class TestIwvValidation:
    def test_analytic_uniform_column(self) -> None:
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        value = _iwv(levels, np.full(5, 0.010))
        expected = 0.010 * 500.0 * 100.0 / GRAVITY
        assert value == pytest.approx(expected, rel=1e-9)

    def test_pressure_order_does_not_matter(self) -> None:
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        q = np.array([0.014, 0.011, 0.008, 0.004, 0.002])
        forward = _iwv(levels, q)
        backward = _iwv(levels[::-1], q[::-1])
        assert forward == pytest.approx(backward, rel=1e-12)

    def test_humidity_unit_scaling_is_exactly_1000x(self) -> None:
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        kg_per_kg = _iwv(levels, np.full(5, 0.010))
        grams_per_kg = _iwv(levels, np.full(5, 10.0))
        assert grams_per_kg == pytest.approx(kg_per_kg * 1000.0, rel=1e-9)

    def test_missing_level_yields_nan_not_a_partial_total(self) -> None:
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        assert np.isnan(_iwv(levels, np.array([0.010, np.nan, 0.010, 0.010, 0.010])))
        # And it must not equal the complete-column value.
        complete = _iwv(levels, np.full(5, 0.010))
        assert not np.isnan(complete)

    def test_dry_column_is_exactly_zero(self) -> None:
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        assert _iwv(levels, np.zeros(5)) == pytest.approx(0.0, abs=1e-12)

    def test_physically_realisable_column_respects_its_saturation_bound(self) -> None:
        """A realisable atmosphere cannot exceed the saturation-limited IWV.

        The bound is derived, not guessed: integrate a fully saturated profile
        over the same pressure range, then check a column that is realistic for
        a tropical monsoon atmosphere stays beneath it.
        """
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        # q_sat at 1000/925/850/700/500 hPa for a warm, wet tropical profile.
        dewpoint = np.array([301.0, 297.0, 291.0, 279.0, 262.0])
        value = _iwv(levels, V.dewpoint_to_specific_humidity(levels, dewpoint))
        saturated = V.dewpoint_to_specific_humidity(levels, dewpoint)
        maximum = _iwv(levels, saturated)
        assert 0.0 < value <= maximum
        assert 0.0 < maximum < 100.0  # published range for extreme tropical air

    def test_supersaturated_input_is_detectable_not_silently_accepted(self) -> None:
        """q above saturation must be visible as exceeding the physical bound."""
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        impossible = np.array([0.030, 0.025, 0.020, 0.012, 0.006])
        temperatures = np.array([293.0, 288.0, 281.0, 268.0, 253.0])
        saturation_limit = V.dewpoint_to_specific_humidity(levels, temperatures)
        # The routine integrates faithfully; the caller is responsible for
        # rejecting the input, and this documents that it is detectable.
        assert np.all(impossible > saturation_limit)
        assert _iwv(levels, impossible) > _iwv(levels, saturation_limit)

    def test_agrees_with_metpy_when_available(self) -> None:
        if not V.metpy_available():
            pytest.skip("MetPy is not installed; no independent reference available")
        levels = np.array([1000.0, 925.0, 850.0, 700.0, 500.0])
        dewpoint = np.array([288.0, 281.0, 273.0, 262.0, 250.0])
        ours = _iwv(levels, V.dewpoint_to_specific_humidity(levels, dewpoint))
        theirs = V.reference_iwv_mm(levels, dewpoint)
        assert theirs is not None
        assert abs(ours - theirs) / theirs <= V.IWV_REL_TOLERANCE

    def test_report_passes(self) -> None:
        report = V.run_iwv_validation()
        assert report.n_fail == 0, [c.detail for c in report.checks if c.status == V.FAIL]
        assert report.validated is True
        assert report.status == V.PASS
        assert report.max_relative_error is not None


# --------------------------------------------------------------------------- #
# Temporal feasibility: the six-frame, 30-minute contract
# --------------------------------------------------------------------------- #
class TestTemporalFeasibility:
    def test_six_consecutive_30_minute_frames_are_feasible(self) -> None:
        report = assess_temporal_feasibility(
            _times_30min(6), source="INSAT-like", data_class="observation"
        )
        assert report.feasible is True
        assert report.native_cadence_minutes == 30.0
        assert report.max_contiguous_run == 6
        assert report.cadence_matches is True
        assert report.provides_required_frames is True

    def test_five_frames_are_one_short(self) -> None:
        report = assess_temporal_feasibility(
            _times_30min(5), source="short", data_class="observation"
        )
        assert report.feasible is False
        assert report.provides_required_frames is False
        assert any("short of the 6" in n for n in report.notes)

    def test_three_hourly_reanalysis_is_infeasible(self) -> None:
        """The core prohibition: IMDAA cannot be upsampled into 30-minute frames."""
        report = assess_temporal_feasibility(
            _times_cadence(8, 180), source="IMDAA", data_class="reanalysis"
        )
        assert report.feasible is False
        assert report.native_cadence_minutes == 180.0
        assert report.max_contiguous_run == 1
        assert report.cadence_matches is False
        joined = " ".join(report.notes)
        assert "NOT upsampled" in joined
        assert "repeating" in joined and "interpolating" in joined

    def test_three_hourly_data_never_reports_feasible_even_when_long(self) -> None:
        report = assess_temporal_feasibility(
            _times_cadence(500, 180), source="IMDAA-long", data_class="reanalysis"
        )
        assert report.distinct_times == 500
        assert report.feasible is False

    def test_gap_breaks_contiguity(self) -> None:
        # 0, 30, 60 then a 60-minute hole, then 120, 150, 180: runs of 3 and 3.
        first = _times_30min(3)
        second = [
            (BASE + dt.timedelta(minutes=m)).isoformat() for m in (120, 150, 180)
        ]
        report = assess_temporal_feasibility(
            first + second, source="gappy", data_class="observation"
        )
        assert report.max_contiguous_run == 3
        assert report.feasible is False
        assert report.largest_gap_minutes == 60.0
        assert any("discontinuous" in n for n in report.notes)

    def test_near_miss_cadence_is_not_accepted(self) -> None:
        """28- or 32-minute cadence is not the contract's 30 minutes."""
        report = assess_temporal_feasibility(
            _times_cadence(8, 28), source="drifting", data_class="observation"
        )
        assert report.cadence_matches is False
        assert report.feasible is False

    def test_empty_series_is_reported_not_fabricated(self) -> None:
        report = assess_temporal_feasibility([], source="empty", data_class="observation")
        assert report.feasible is False
        assert report.distinct_times == 0
        assert report.max_contiguous_run == 0
        assert report.native_cadence_minutes is None
        assert any("snapshot" in n for n in report.notes)

    def test_duplicate_and_unsorted_times_do_not_change_the_verdict(self) -> None:
        ordered = _times_30min(6)
        shuffled = list(reversed(ordered)) + ordered[:2]
        a = assess_temporal_feasibility(ordered, source="s", data_class="observation")
        b = assess_temporal_feasibility(shuffled, source="s", data_class="observation")
        assert a.feasible == b.feasible is True
        assert a.distinct_times == b.distinct_times == 6

    def test_declared_data_classes_are_all_accepted(self) -> None:
        for data_class in DATA_CLASSES:
            report = assess_temporal_feasibility(
                _times_30min(6), source="s", data_class=data_class
            )
            assert report.data_class == data_class
            # Only a true observation can be feasible; every other class is
            # measured but can never satisfy an observational requirement.
            if data_class == "observation":
                assert report.feasible is True
                assert not any(
                    "not an instrument observation" in n
                    or "generated, not observed" in n
                    for n in report.notes
                )
            else:
                assert report.feasible is False
                assert any(
                    "not an instrument observation" in n
                    or "generated, not observed" in n
                    for n in report.notes
                ), data_class

    def test_synthetic_data_is_never_temporally_feasible(self) -> None:
        """Generated fields cannot satisfy an observational cadence contract."""
        report = assess_temporal_feasibility(
            _times_30min(6), source="generated", data_class="synthetic"
        )
        assert report.cadence_matches is True       # the cadence is right
        assert report.provides_required_frames is True  # and the run is long enough
        assert report.feasible is False             # but it is not observation
        assert any("generated, not observed" in n for n in report.notes)

    def test_unknown_data_class_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="unknown data_class"):
            assess_temporal_feasibility(_times_30min(6), source="s", data_class="guess")

    def test_channels_and_spatial_coverage_are_carried(self) -> None:
        report = assess_temporal_feasibility(
            _times_30min(6), source="s", data_class="observation",
            channels_available=["tir1_bt"], channels_missing=["cape"],
            spatial_coverage="77.5-80.5E 29.0-31.5N",
        )
        assert report.channels_available == ["tir1_bt"]
        assert report.channels_missing == ["cape"]
        assert report.spatial_coverage == "77.5-80.5E 29.0-31.5N"
        assert report.to_dict()["spatial_coverage"] == "77.5-80.5E 29.0-31.5N"

    def test_api_offers_no_upsampling_parameter(self) -> None:
        """Guard the central prohibition at the signature level."""
        import inspect

        parameters = inspect.signature(assess_temporal_feasibility).parameters
        for forbidden in ("upsample", "resample", "interpolate", "repeat", "step"):
            assert forbidden not in parameters, f"{forbidden!r} must not be exposed"

    def test_longest_contiguous_run_helper(self) -> None:
        base_times = [BASE + dt.timedelta(minutes=30 * i) for i in range(4)]
        assert longest_contiguous_run(base_times) == 4
        assert longest_contiguous_run([]) == 0
        assert longest_contiguous_run([BASE]) == 1
        broken = [BASE, BASE + dt.timedelta(minutes=30), BASE + dt.timedelta(minutes=90)]
        assert longest_contiguous_run(broken) == 2

    def test_cadence_matcher_is_exact(self) -> None:
        assert cadence_matches_contract(30.0, 30) is True
        assert cadence_matches_contract(28.0, 30) is False
        assert cadence_matches_contract(180.0, 30) is False
        assert cadence_matches_contract(None, 30) is False

    def test_report_serialises_every_check(self) -> None:
        payload = V.run_iwv_validation().to_dict()
        assert payload["feature"] == "iwv"
        assert len(payload["checks"]) >= 6
        names = {c["name"] for c in payload["checks"]}
        assert "missing_level_yields_nan" in names
        assert "humidity_unit_scaling" in names
        assert "pressure_order_invariance" in names
        assert "dry_column_is_zero" in names

    def test_missing_metpy_downgrades_only_the_oracle_check(self, monkeypatch) -> None:
        monkeypatch.setattr(V, "_metpy", lambda: (None, None))
        assert V.reference_iwv_mm([1000, 850, 700], [288, 275, 260]) is None
        report = V.run_iwv_validation()
        # The analytic properties are oracle-free, so the feature still validates.
        assert report.validated is True
        assert report.n_fail == 0
        assert report.n_no_reference == 1
        assert report.reference_implementation is None

    def test_dewpoint_round_trip_is_exact(self) -> None:
        p = np.array([1000.0, 925.0, 850.0, 700.0, 500.0, 300.0])
        dewpoint = np.array([295.0, 288.0, 281.0, 268.0, 253.0, 230.0])
        q = V.dewpoint_to_specific_humidity(p, dewpoint)
        assert np.allclose(V.sounding_to_dewpoint_k(p, q), dewpoint, atol=1e-8)
        assert np.all(q > 0)
        assert np.all(q < 0.05)



# --------------------------------------------------------------------------- #
# Readiness: scientific permission, not just tensor shape
# --------------------------------------------------------------------------- #
def _ideal_readiness(**overrides):
    """A dataset that satisfies every gate; override one thing per test."""
    from app.ingestion.realtime.readiness import (
        REQUIRED_CHANNELS,
        REQUIRED_LABELS,
        assess_readiness,
    )

    kwargs = dict(
        dataset_name="ideal", is_synthetic=False, n_records=500, n_stations=10,
        available_channels=list(REQUIRED_CHANNELS), valid_times=_times_30min(6),
        data_class="observation", spatial_coverage="77.5-80.5E 29.0-31.5N",
        required_labels=REQUIRED_LABELS, available_labels=REQUIRED_LABELS,
        cape_validation=V.PASS, iwv_validation=V.PASS,
    )
    kwargs.update(overrides)
    return assess_readiness(**kwargs)


class TestReadinessScientificGate:
    def test_fully_satisfying_dataset_is_permitted(self) -> None:
        report = _ideal_readiness()
        assert report.technically_permitted is True
        assert report.scientifically_permitted is True
        assert report.training_permitted is True
        assert report.validation_passed is True
        assert report.labels_complete is True
        assert report.temporally_feasible is True
        assert report.scientific_blockers == []

    def test_shape_alone_is_not_permission(self) -> None:
        """A 12-channel tensor with a 3-hourly cadence must not be trainable."""
        report = _ideal_readiness(valid_times=_times_cadence(8, 180),
                                  data_class="reanalysis")
        assert report.channels_missing == []
        assert report.temporally_feasible is False
        assert report.technically_permitted is False
        assert report.training_permitted is False
        assert any("temporal" in b for b in report.scientific_blockers)

    def test_unvalidated_features_block_training(self) -> None:
        report = _ideal_readiness(cape_validation=None, iwv_validation=None)
        assert report.validation_reported is False
        assert report.validation_passed is False
        assert report.training_permitted is False
        assert any("validation has not been reported" in b
                   for b in report.scientific_blockers)

    def test_failed_feature_validation_blocks_training(self) -> None:
        report = _ideal_readiness(cape_validation=V.FAIL, iwv_validation=V.PASS)
        assert report.validation_passed is False
        assert report.training_permitted is False
        assert any("CAPE validation status is 'fail'" in b
                   for b in report.scientific_blockers)

    def test_no_reference_status_blocks_training(self) -> None:
        report = _ideal_readiness(cape_validation=V.PASS, iwv_validation=V.NO_REFERENCE)
        assert report.training_permitted is False
        assert any("IWV validation status is 'no_reference_available'" in b
                   for b in report.scientific_blockers)

    def test_partial_validation_does_not_count_as_passed(self) -> None:
        report = _ideal_readiness(iwv_validation=None)
        assert report.validation_reported is True   # CAPE was reported
        assert report.validation_passed is False    # but not both
        assert report.training_permitted is False


    def test_missing_labels_block_training(self) -> None:
        from app.ingestion.realtime.readiness import REQUIRED_LABELS

        report = _ideal_readiness(available_labels=list(REQUIRED_LABELS)[:3])
        assert report.labels_complete is False
        assert len(report.labels_missing) == 2
        assert report.training_permitted is False
        assert any("missing required targets" in b for b in report.scientific_blockers)

    def test_missing_channels_block_training(self) -> None:
        from app.ingestion.realtime.readiness import REQUIRED_CHANNELS

        report = _ideal_readiness(available_channels=list(REQUIRED_CHANNELS)[:6])
        assert report.channels_complete is False
        assert report.training_permitted is False

    def test_synthetic_data_is_never_scientifically_permitted(self) -> None:
        report = _ideal_readiness(is_synthetic=True)
        assert report.training_permitted is False
        assert any("synthetic" in b for b in report.scientific_blockers)

    def test_absent_valid_times_block_training(self) -> None:
        report = _ideal_readiness(valid_times=(), distinct_time_values=())
        assert report.temporal is None
        assert report.technically_permitted is False
        assert report.training_permitted is False
        assert any("no genuine valid times" in b for b in report.scientific_blockers)

    def test_undeclared_spatial_coverage_blocks_training(self) -> None:
        # Readiness reports the gap in `notes`; the authoritative blocker, which
        # includes the actual-vs-requested comparison, is emitted by the training
        # gate (see the TestTrainingGate coverage tests).
        report = _ideal_readiness(spatial_coverage=None)
        assert report.training_permitted is False
        assert any("spatial coverage was not declared" in n for n in report.notes)

    def test_report_serialises_every_phase8_field(self) -> None:
        payload = _ideal_readiness().to_dict()
        for key in (
            "temporal", "spatial_coverage", "required_labels", "labels_present",
            "labels_missing", "cape_validation", "iwv_validation",
            "validation_reported", "validation_passed", "temporally_feasible",
            "labels_complete", "channels_complete", "technically_permitted",
            "scientifically_permitted", "training_permitted", "scientific_blockers",
        ):
            assert key in payload, key
        assert payload["training_permitted"] is True
        assert payload["temporal"]["feasible"] is True

    def test_three_hourly_imdaa_is_blocked_end_to_end(self) -> None:
        """The headline Phase 8 result, exercised through the public API."""
        from app.ingestion.realtime.readiness import (
            REQUIRED_LABELS,
            assess_readiness,
        )

        report = assess_readiness(
            dataset_name="IMDAA", is_synthetic=False, n_records=1000, n_stations=0,
            available_channels=["cape", "iwv"], valid_times=_times_cadence(40, 180),
            data_class="reanalysis", spatial_coverage="77.5-80.5E 29.0-31.5N",
            required_labels=REQUIRED_LABELS, available_labels=[],
            cape_validation=V.PASS, iwv_validation=V.PASS,
        )
        assert report.channels_missing != []            # only 2 of 12 channels
        assert report.temporally_feasible is False       # 3-hourly, not 30-minute
        assert report.training_permitted is False
        assert report.temporal["native_cadence_minutes"] == 180.0

    def test_phase6_heuristic_contract_is_preserved(self) -> None:
        """Existing callers that pass only ``distinct_times`` keep working."""
        from app.ingestion.realtime.readiness import REQUIRED_CHANNELS, assess_readiness

        report = assess_readiness(
            dataset_name="full", is_synthetic=False, n_records=100, n_stations=5,
            available_channels=list(REQUIRED_CHANNELS), distinct_times=50,
        )
        assert report.verdict == "ready"
        assert report.can_train is True
        # ...but the new scientific gate still refuses, because nothing was
        # validated and no genuine cadence was measured.
        assert report.training_permitted is False
        assert report.temporal is None



# --------------------------------------------------------------------------- #
# Phase 8.1 - the training gate
# --------------------------------------------------------------------------- #
def _real_cube(
    *,
    times: int = 6,
    minutes: int = 30,
    channels: int = 12,
    labels: Sequence[str] = ("thunderstorm", "rain_class", "cloudburst", "flood", "flood_soft"),
    synthetic: bool = False,
    spatial: str | None = "78-79E 29-30N",
    channel_units: bool = True,
    provenance: bool = True,
    source_file: object | None = None,
    source_sha256: str | None = None,
    extra_source_files: Sequence[object] = (),
) -> ObservationCube:
    """A minimal cube whose provenance states exactly what it is.

    Built here rather than downloaded so the gate can be exercised against known,
    *declared* provenance. ``synthetic=False`` is an explicit test fixture claim,
    never a statement that these are real observations. The default ``spatial``
    declaration matches the cube's own raster extent, so a fully eligible fixture
    has no coverage shortfall.
    """
    from app.grid import GridSpec
    from app.ingestion.base import ObservationCube, Provenance, source_file_from_disk

    grid = GridSpec.from_bbox([78.0, 29.0, 79.0, 30.0], res_km=20.0)
    stamps = [BASE + dt.timedelta(minutes=minutes * i) for i in range(times)]
    # Absent channels are NaN, not 0.0: the project's missing-data contract says a
    # missing channel must never be filled with a value, and the gate measures
    # presence with ``isfinite``.
    data = np.full((times, 12, *grid.shape), np.nan, dtype=np.float32)
    data[:, :channels] = 1.0
    cube_labels = {name: np.zeros((times, *grid.shape), dtype=np.float32) for name in labels}
    metadata: dict[str, object] = {"spatial_coverage": spatial} if spatial else {}
    if channel_units:
        from app.physics import CHANNELS

        metadata["channel_units"] = {spec.name: spec.unit for spec in CHANNELS}
    records = (
        [
            Provenance(
                source="FIXTURE" if not synthetic else "SYNTHETIC",
                product="phase-8 gate fixture",
                valid_from=stamps[0],
                valid_to=stamps[-1],
                is_synthetic=synthetic,
                attribution="test fixture" if not synthetic else "synthetic test fixture",
                source_sha256=source_sha256,
                source_path=str(source_file) if source_file else None,
                source_bytes_available=source_sha256 is not None,
                provider="Test provider",
                acquired_at=stamps[0],
                channel_units=dict(metadata.get("channel_units", {})),
                coverage=spatial,
                source_files=[source_file_from_disk(f) for f in extra_source_files],
            )
        ]
        if provenance
        else []
    )
    return ObservationCube(
        grid=grid,
        times=stamps,
        channels=data,
        provenance=records,
        labels=cube_labels,
        metadata=metadata,
    )

class TestTrainingSafeguards:
    def test_no_production_checkpoint_is_created_or_replaced(self) -> None:
        """Validation work must never touch the shipped checkpoint."""
        from pathlib import Path

        from app.models.registry import CHECKPOINT_NAME

        checkpoint = Path("data") / CHECKPOINT_NAME
        if checkpoint.exists():
            before = (checkpoint.stat().st_mtime_ns, checkpoint.stat().st_size)
            _ideal_readiness()
            assert _ideal_readiness().training_permitted is True  # no side effects
            after = (checkpoint.stat().st_mtime_ns, checkpoint.stat().st_size)
            assert before == after, "the production checkpoint was modified"

    def test_validation_modules_do_not_import_training(self) -> None:
        """The validation and readiness layers must stay free of training code."""
        import ast
        from pathlib import Path

        base = Path("app") / "ingestion" / "realtime"
        for name in ("validation.py", "temporal.py", "readiness.py"):
            tree = ast.parse((base / name).read_text(encoding="utf-8"))
            for node in ast.walk(tree):
                if isinstance(node, ast.ImportFrom) and node.module:
                    assert not node.module.startswith("app.training"), (
                        f"{name} imports app.training.{node.module}"
                    )
                    assert not node.module.startswith("app.models.registry")

    def test_synthetic_inputs_never_reach_a_permitted_verdict(self) -> None:
        from app.ingestion.realtime.readiness import REQUIRED_LABELS

        for synthetic in (True, False):
            report = _ideal_readiness(
                is_synthetic=synthetic,
                available_labels=list(REQUIRED_LABELS),
            )
            if synthetic:
                assert report.training_permitted is False

    def test_gates_are_all_required_simultaneously(self) -> None:
        """Each single failure must independently block permission."""
        failures = {
            "cadence": dict(valid_times=_times_cadence(8, 180)),
            "validation": dict(cape_validation=None),
            "labels": dict(available_labels=[]),
            "spatial": dict(spatial_coverage=None),
            "synthetic": dict(is_synthetic=True),
        }
        for name, override in failures.items():
            report = _ideal_readiness(**override)
            assert report.training_permitted is False, f"{name} did not block training"

    def test_readiness_never_fabricates_a_channel(self) -> None:
        report = _ideal_readiness(available_channels=["cape", "iwv"])
        # Reported in the canonical channel order (iwv precedes cape in CHANNELS),
        # so the present set is deterministic rather than echoing the input.
        assert set(report.channels_present) == {"cape", "iwv"}
        assert len(report.channels_missing) == 10
        assert report.training_permitted is False
        for missing in report.channels_missing:
            assert missing in report.blockers
            assert report.blockers[missing]



class TestDatasetDescriptor:
    def test_authenticity_comes_from_provenance_not_a_filename(self, tmp_path) -> None:
        """A reassuring directory name must not make generated data look real."""
        cube = _real_cube(synthetic=True)
        descriptor = describe_dataset([cube])
        assert descriptor.is_synthetic is True
        assert descriptor.data_class == "synthetic"
        # Nothing in the descriptor is derived from a path.
        assert "FIXTURE" not in descriptor.dataset_name

    def test_declared_real_provenance_is_read(self) -> None:
        descriptor = describe_dataset([_real_cube(synthetic=False)])
        assert descriptor.is_synthetic is False
        assert descriptor.data_class == "real"
        assert any("synthetic=False" in line for line in descriptor.provenance_summary)

    def test_missing_provenance_is_treated_as_synthetic(self) -> None:
        """Absence of evidence must never be read as evidence of observation."""
        from app.grid import GridSpec

        grid = GridSpec.from_bbox([78.0, 29.0, 79.0, 30.0], res_km=20.0)
        bare = ObservationCube(
            grid=grid,
            times=[BASE + dt.timedelta(minutes=30 * i) for i in range(6)],
            channels=np.ones((6, 12, *grid.shape), dtype=np.float32),
        )
        descriptor = describe_dataset([bare])
        assert descriptor.is_synthetic is True
        assert descriptor.data_class == "synthetic"

    def test_a_single_synthetic_cube_taints_the_set(self) -> None:
        mixed = [_real_cube(synthetic=False), _real_cube(synthetic=True)]
        assert describe_dataset(mixed).is_synthetic is True

    def test_channels_are_measured_from_finite_values(self) -> None:
        descriptor = describe_dataset([_real_cube(channels=4)])
        assert len(descriptor.channels_present) == 4
        assert len(descriptor.channels_present) < 12

    def test_labels_are_read_from_the_cube(self) -> None:
        descriptor = describe_dataset([_real_cube(labels=("cloudburst",))])
        assert descriptor.labels_present == ["cloudburst"]

    def test_spatial_declaration_is_required_not_guessed(self) -> None:
        """Phase 8.2 removed the GridSpec fallback: coverage must be declared."""
        assert describe_dataset([_real_cube(spatial=None)]).spatial_coverage is None
        assert describe_dataset([_real_cube(spatial=None)]).coverage_declared is False
        assert describe_dataset([_real_cube(spatial="78-79E 29-30N")]).coverage_declared is True

    def test_empty_cube_list_is_synthetic_by_default(self) -> None:
        descriptor = describe_dataset([])
        assert descriptor.is_synthetic is True
        assert descriptor.n_cubes == 0



class TestTrainingGate:
    """Each Phase 8 criterion, tested independently against the real entry point."""

    def _eligible(self) -> list[ObservationCube]:
        return [_real_cube(times=6, minutes=30, channels=12, synthetic=False)]

    def test_fully_eligible_dataset_is_permitted(self, tmp_path) -> None:
        report = enforce_training_gate(
            self._eligible(),
            mode=PRODUCTION,
            output_dir=str(tmp_path / "out"),
            cape_validation=V.PASS,
            iwv_validation=V.PASS,
        )
        assert report["technically_permitted"] is True
        assert report["scientifically_permitted"] is True
        assert report["scientific_blockers"] == []

    def test_synthetic_data_is_blocked_in_production(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(synthetic=True)],
                mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS,
                iwv_validation=V.PASS,
            )
        report = excinfo.value.report
        assert any("synthetic" in b for b in report["scientific_blockers"])
        assert report["scientifically_permitted"] is False
        assert "TRAINING BLOCKED" in excinfo.value.render()

    def test_missing_channels_block_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(channels=6)],
                mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        report = excinfo.value.report
        assert len(report["channels_missing"]) == 6
        assert any("missing model channel" in a for a in report["next_actions"])

    def test_missing_labels_block_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(labels=("cloudburst",))],
                mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        assert len(excinfo.value.report["labels_missing"]) == 4

    def test_three_hourly_data_block_training(self, tmp_path) -> None:
        """The headline case: genuine data, wrong cadence, still blocked."""
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(times=8, minutes=180)],
                mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        report = excinfo.value.report
        assert report["temporal"]["native_cadence_minutes"] == 180.0
        assert report["temporal"]["feasible"] is False
        assert any("180-minute" in a for a in report["next_actions"])
        assert any("do not repeat or interpolate" in a for a in report["next_actions"])

    def test_too_few_frames_block_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked):
            enforce_training_gate(
                [_real_cube(times=5)],
                mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )


    def test_absent_validation_blocks_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                self._eligible(), mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=None, iwv_validation=None,
            )
        assert any("validation has not been reported" in b
                   for b in excinfo.value.report["scientific_blockers"])

    def test_failed_validation_blocks_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                self._eligible(), mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=V.FAIL, iwv_validation=V.PASS,
            )
        assert any("CAPE validation status is 'fail'" in b
                   for b in excinfo.value.report["scientific_blockers"])

    def test_unavailable_reference_blocks_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                self._eligible(), mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.NO_REFERENCE,
            )
        assert any("no independent reference" in a
                   for a in excinfo.value.report["next_actions"])

    def test_missing_spatial_declaration_blocks_training(self, tmp_path) -> None:
        """Phase 8.2: a GridSpec alone is no longer accepted as coverage.

        A ``GridSpec`` records where a cube was placed on the model raster, not
        that the source data covered that area.
        """
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(spatial=None)], mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        report = excinfo.value.report
        assert report["spatial_coverage"] is None
        assert any(
            "no explicit spatial coverage declaration" in b
            for b in report["scientific_blockers"]
        )
        assert any("'spatial_coverage'" in a for a in report["next_actions"])

    def test_declared_coverage_larger_than_the_data_blocks_training(self, tmp_path) -> None:
        """Declared coverage is compared against actual extent, not assumed."""
        cube = _real_cube(spatial="77-80E 28-31N")  # cube raster is only 78-79E 29-30N
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [cube], mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        report = excinfo.value.report
        assert report["actual_coverage"] == {
            "min_lon": 78.0, "min_lat": 29.0, "max_lon": 79.0, "max_lat": 30.0
        }
        assert report["coverage_gap"]["west"] == pytest.approx(1.0)
        assert report["coverage_gap"]["east"] == pytest.approx(1.0)
        assert report["coverage_gap"]["north"] == pytest.approx(1.0)
        assert any("exceeds the actual data extent" in b
                   for b in report["scientific_blockers"])

    def test_declared_coverage_within_the_data_is_accepted(self, tmp_path) -> None:
        """A declaration *smaller* than the raster is fine: it is supported."""
        report = enforce_training_gate(
            [_real_cube(spatial="78.2-78.8E 29.2-29.8N")], mode=PRODUCTION,
            output_dir=str(tmp_path / "out"),
            cape_validation=V.PASS, iwv_validation=V.PASS,
        )
        assert report["coverage_gap"] is None
        assert report["scientifically_permitted"] is True

    def test_unparseable_coverage_declaration_blocks_training(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(spatial="somewhere in Uttarakhand")], mode=PRODUCTION,
                output_dir=str(tmp_path / "out"),
                cape_validation=V.PASS, iwv_validation=V.PASS,
            )
        assert any("could not be parsed" in b
                   for b in excinfo.value.report["scientific_blockers"])

    def test_unknown_mode_is_rejected(self, tmp_path) -> None:
        with pytest.raises(ValueError, match="unknown training mode"):
            enforce_training_gate(
                self._eligible(), mode="yolo", output_dir=str(tmp_path / "out")
            )

    def test_mismatched_cadence_contract_is_rejected(self, tmp_path) -> None:
        with pytest.raises(ValueError, match="canonical cadence"):
            enforce_training_gate(
                self._eligible(), mode=PRODUCTION,
                output_dir=str(tmp_path / "out"), frame_minutes=15,
            )

    def test_failure_report_is_actionable(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(channels=6, times=5, minutes=180)],
                mode=PRODUCTION, output_dir=str(tmp_path / "out"),
                cape_validation=None, iwv_validation=V.FAIL,
            )
        report = excinfo.value.report
        assert report["dataset_name"]
        assert report["data_class"] == "real"
        assert report["provenance_summary"]
        assert report["channels_missing"]
        assert report["temporal"]["native_cadence_minutes"] == 180.0
        assert report["cape_validation"] is None
        assert len(report["next_actions"]) >= 3
        rendered = excinfo.value.render()
        for heading in ("dataset", "cadence", "channels", "labels", "next action"):
            assert heading in rendered
        assert "No model, optimiser or checkpoint was created" in rendered



class TestSyntheticDemoMode:
    """The demonstration mode is separate from production and cannot escalate."""

    def test_demo_mode_allows_generated_data_in_a_demo_path(self, tmp_path) -> None:
        from app.training.gate import synthetic_demo_output_dir

        report = enforce_training_gate(
            [_real_cube(synthetic=True)],
            mode=SYNTHETIC_DEMO,
            output_dir=synthetic_demo_output_dir(str(tmp_path / "out")),
        )
        assert report["mode"] == SYNTHETIC_DEMO
        assert report["technically_permitted"] is False   # it is not eligible
        assert "synthetic demonstration" in report["next_actions"][0]

    def test_demo_mode_refuses_a_production_output_path(self, tmp_path) -> None:
        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(synthetic=True)],
                mode=SYNTHETIC_DEMO,
                output_dir=str(tmp_path / "production-model"),
            )
        assert "synthetic-demo" in str(excinfo.value)
        assert any("synthetic-demo" in a for a in excinfo.value.report["next_actions"])

    def test_demo_mode_refuses_real_data(self, tmp_path) -> None:
        """Real data must go through production, where it is validated."""
        from app.training.gate import synthetic_demo_output_dir

        with pytest.raises(TrainingBlocked) as excinfo:
            enforce_training_gate(
                [_real_cube(synthetic=False)],
                mode=SYNTHETIC_DEMO,
                output_dir=synthetic_demo_output_dir(str(tmp_path / "out")),
            )
        assert "production mode" in str(excinfo.value)

    def test_demo_dir_helper_always_marks_the_path(self, tmp_path) -> None:
        from app.training.gate import synthetic_demo_output_dir

        produced = synthetic_demo_output_dir("data/models/sihps")
        assert "synthetic-demo" in produced
        assert not produced.endswith("sihps")

    def test_no_config_flag_can_enable_synthetic_in_production(self) -> None:
        """There is no bypass: the mode string is the only lever."""
        import inspect

        from app.training.train import TrainConfig

        fields = set(TrainConfig.__dataclass_fields__)
        # No field may mean "allow synthetic data in production".
        for forbidden in ("allow_synthetic", "bypass", "skip_gate", "force", "no_validate"):
            assert forbidden not in fields, forbidden
        assert "mode" in fields
        signature = inspect.signature(TrainConfig)
        assert signature.parameters["mode"].default == SYNTHETIC_DEMO



class TestBlockedRunsLeaveNoArtefacts:
    """The whole point: a blocked run must write nothing at all."""

    def test_production_run_on_synthetic_data_is_blocked_and_writes_nothing(
        self, tmp_path
    ) -> None:
        """`load_training_cubes` only ever makes synthetic data, so a production
        run today is always blocked - and must not leave a checkpoint behind."""
        from app.models.registry import CHECKPOINT_NAME
        from app.training.train import TrainConfig, train

        out = tmp_path / "production-model"
        config = TrainConfig(
            n_events=1, epochs=1, max_steps=1, preset="lite",
            output_dir=str(out), mode=PRODUCTION,
        )
        with pytest.raises(TrainingBlocked) as excinfo:
            train(config)

        assert not (out / CHECKPOINT_NAME).exists()
        assert not out.exists() or not any(out.iterdir())
        assert "TRAINING BLOCKED" in excinfo.value.render()

    def test_blocked_run_does_not_touch_an_existing_checkpoint(self, tmp_path) -> None:
        """An existing checkpoint must survive a blocked run byte-for-byte."""
        import hashlib

        from app.models.registry import CHECKPOINT_NAME, build_model, save_checkpoint
        from app.training.train import TrainConfig, train

        out = tmp_path / "production-model"
        out.mkdir(parents=True)
        model = build_model(preset="lite")
        save_checkpoint(model, out)
        checkpoint = out / CHECKPOINT_NAME
        before = hashlib.sha256(checkpoint.read_bytes()).hexdigest()
        assert checkpoint.exists()

        config = TrainConfig(
            n_events=1, epochs=1, max_steps=1, preset="lite",
            output_dir=str(out), mode=PRODUCTION,
        )
        with pytest.raises(TrainingBlocked):
            train(config)

        after = hashlib.sha256(checkpoint.read_bytes()).hexdigest()
        assert before == after, "the existing checkpoint was modified by a blocked run"
        assert not (out / "training_report.json").exists()

    def test_demo_run_is_redirected_away_from_the_production_path(self, tmp_path) -> None:
        """A demo run must land under a demo-scoped directory, never on the model path."""
        from app.config import get_settings
        from app.training.gate import DEMO_DIR_MARKER
        from app.training.train import TrainConfig, _run_data_gate, load_training_cubes

        production_path = tmp_path / "production-model"
        config = TrainConfig(
            n_events=1, epochs=1, max_steps=1, preset="lite",
            output_dir=str(production_path), mode=SYNTHETIC_DEMO,
        )
        cubes, _ids, _terrain = load_training_cubes(config, get_settings().grid)
        # The gate is consulted on the real cubes and permits the demo run.
        report = _run_data_gate(cubes, config)
        assert report["mode"] == SYNTHETIC_DEMO
        # ...and the directory a demo run would use is marked as a demo, so the
        # production model path itself is never a legal target.
        demo_dir = _demo_output_for(config)
        assert DEMO_DIR_MARKER in demo_dir
        assert demo_dir != str(production_path)

    def test_legacy_can_train_and_verdict_api_is_unchanged(self, tmp_path) -> None:
        """Phase 6 callers keep working exactly as before."""
        from app.ingestion.realtime.readiness import REQUIRED_CHANNELS, assess_readiness

        report = assess_readiness(
            dataset_name="full", is_synthetic=False, n_records=100, n_stations=5,
            available_channels=list(REQUIRED_CHANNELS), distinct_times=50,
        )
        assert report.verdict == "ready"
        assert report.can_train is True
        payload = report.to_dict()
        assert payload["can_train"] is True
        assert payload["verdict"] == "ready"
        # ...and the new fields are additive, not replacements.
        assert "training_permitted" in payload
        assert payload["training_permitted"] is False


def _demo_output_for(config) -> str:
    """The output directory a demo run would actually use."""
    from pathlib import Path

    from app.training.gate import DEMO_DIR_MARKER

    if DEMO_DIR_MARKER in config.output_dir:
        return config.output_dir
    return str(Path(config.output_dir) / DEMO_DIR_MARKER)



# --------------------------------------------------------------------------- #
# Phase 8.2 - evaluation integrity and provenance
# --------------------------------------------------------------------------- #
class TestEvaluationIntegrity:
    def test_synthetic_data_cannot_be_evaluated_as_observational(self) -> None:
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=True)], requested_mode=OBSERVATIONAL
            )
        report = excinfo.value.report
        assert report["verified_is_synthetic"] is True
        assert report["data_class"] == "synthetic"
        assert any("synthetic" in a for a in report["next_actions"])
        assert "EVALUATION BLOCKED" in excinfo.value.render()

    def test_caller_flag_cannot_override_provenance(self) -> None:
        """The Phase 8.2 core: ``is_synthetic=False`` is not evidence."""
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=True)],
                requested_mode=OBSERVATIONAL,
                claimed_is_synthetic=False,   # the old --observational flag
            )
        report = excinfo.value.report
        assert report["claimed_is_synthetic"] is False
        assert report["verified_is_synthetic"] is True
        assert report["claim_contradicts_provenance"] is True
        assert any("the evidence wins" in a for a in report["next_actions"])

    def test_false_flag_on_real_data_is_also_a_contradiction(self) -> None:
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=False)],
                requested_mode=OBSERVATIONAL,
                claimed_is_synthetic=True,
            )
        assert excinfo.value.report["claim_contradicts_provenance"] is True

    def test_missing_provenance_fails_closed(self) -> None:
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(provenance=False)], requested_mode=OBSERVATIONAL
            )
        checks = {c["name"]: c for c in excinfo.value.report["checks"]}
        assert checks["provenance_present"]["passed"] is False
        assert "never inferred" in checks["provenance_present"]["detail"]

    def test_missing_channel_units_fails_closed(self) -> None:
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(channel_units=False)], requested_mode=OBSERVATIONAL
            )
        checks = {c["name"]: c for c in excinfo.value.report["checks"]}
        assert checks["channel_units_declared"]["passed"] is False

    def test_contradictory_synthetic_status_is_detected(self) -> None:
        """Attribution saying 'synthetic' while is_synthetic=False is tampering."""
        from app.grid import GridSpec
        from app.ingestion.base import ObservationCube, Provenance

        grid = GridSpec.from_bbox([78.0, 29.0, 79.0, 30.0], res_km=20.0)
        stamps = [BASE + dt.timedelta(minutes=30 * i) for i in range(6)]
        tampered = ObservationCube(
            grid=grid,
            times=stamps,
            channels=np.ones((6, 12, *grid.shape), dtype=np.float32),
            provenance=[
                Provenance(
                    source="IMDAA",
                    product="claimed real",
                    valid_from=stamps[0],
                    valid_to=stamps[-1],
                    is_synthetic=False,             # tampered
                    attribution="synthetic replica",  # but says synthetic
                )
            ],
            metadata={
                "spatial_coverage": "78-79E 29-30N",
                "channel_units": {s.name: s.unit for s in __import__("app.physics", fromlist=["CHANNELS"]).CHANNELS},
            },
        )
        checks = {c["name"]: c for c in verify_provenance([tampered])}
        assert checks["synthetic_status_consistent"]["passed"] is False
        assert "contradictory" in checks["synthetic_status_consistent"]["detail"]
        with pytest.raises(EvaluationBlocked):
            enforce_evaluation_gate([tampered], requested_mode=OBSERVATIONAL)

    def test_mixed_real_and_synthetic_is_not_observational(self) -> None:
        """One generated cube taints the set, in evaluation as in training."""
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=False), _real_cube(synthetic=True)],
                requested_mode=OBSERVATIONAL,
            )
        assert excinfo.value.report["verified_is_synthetic"] is True

    def test_fully_verified_dataset_is_permitted(self, tmp_path) -> None:
        """A dataset whose real bytes hash to its recorded digest passes."""
        from app.ingestion.realtime.provenance import file_sha256

        source = tmp_path / "source.bin"
        source.write_bytes(b"authentic source bytes")
        report = enforce_evaluation_gate(
            [_real_cube(synthetic=False, source_file=source,
                        source_sha256=file_sha256(source))],
            requested_mode=OBSERVATIONAL,
            claimed_is_synthetic=False,
        )
        assert report["verified_is_synthetic"] is False
        assert report["n_failed_checks"] == 0
        assert all(c["passed"] for c in report["checks"])

    def test_unknown_mode_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="unknown evaluation mode"):
            enforce_evaluation_gate([_real_cube()], requested_mode="whatever")



class TestSyntheticEvaluationSeparation:
    def test_demo_mode_allows_synthetic_data_in_a_demo_path(self, tmp_path) -> None:
        report = enforce_evaluation_gate(
            [_real_cube(synthetic=True)],
            requested_mode=SYNTHETIC_EVAL,
            output=str(tmp_path / "synthetic-demo" / "report.json"),
        )
        assert report["verified_is_synthetic"] is True
        assert "may not update official skill summaries" in report["next_actions"][0]

    def test_demo_mode_refuses_a_shared_output_path(self, tmp_path) -> None:
        """A synthetic report must never land on the observational report path."""
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=True)],
                requested_mode=SYNTHETIC_EVAL,
                output=str(tmp_path / "official-report.json"),
            )
        assert "synthetic-demo" in str(excinfo.value)

    def test_demo_mode_refuses_real_data(self, tmp_path) -> None:
        """Real data must be evaluated observationally, not as a demo."""
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=False)],
                requested_mode=SYNTHETIC_EVAL,
                output=str(tmp_path / "synthetic-demo" / "r.json"),
            )
        assert "observational mode" in str(excinfo.value)

    def test_cli_redirects_demo_reports_into_a_separate_directory(self, tmp_path) -> None:
        from app.training.evaluate import EvalConfig

        config = EvalConfig(
            mode=SYNTHETIC_EVAL, n_events=1, split="test", allow_untrained=True,
            output=str(tmp_path / "official.json"),
        )
        from pathlib import Path

        from app.training.gate import EVAL_DEMO_DIR_MARKER

        redirected = str(
            Path(config.output).parent / EVAL_DEMO_DIR_MARKER / Path(config.output).name
        )
        assert EVAL_DEMO_DIR_MARKER in redirected
        assert redirected != config.output


class TestEvaluationReportIntegrity:
    def test_report_records_the_verified_not_claimed_label(self) -> None:
        """The written report must never repeat an unverified caller claim."""
        from app.training.evaluate import EvalConfig, evaluate

        result = evaluate(
            EvalConfig(
                mode=SYNTHETIC_EVAL, n_events=1, split="test", allow_untrained=True,
                output=None,
            )
        )
        assert result["is_synthetic"] is True
        assert result["is_synthetic_claimed_by_caller"] is True
        assert result["integrity"]["verified_is_synthetic"] is True
        assert result["skill_claim_permitted"] is False
        assert "SYNTHETIC DEMO" in result["validation_status"]


class TestIwvFullColumnScope:
    """What the IWV number is, and what full-column validation would need."""

    #: A realistic 20-level tropical profile, 1000 -> 1 hPa.
    FULL_P = np.array(
        [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200,
         150, 100, 70, 50, 30, 20, 10, 5, 2, 1], dtype="float64"
    )
    FULL_TD = np.array(
        [295, 289, 281, 270, 262, 252, 241, 231, 224, 217,
         208, 199, 196, 195, 195, 194, 193, 192, 191, 190], dtype="float64"
    )

    def test_integrator_is_correct_over_a_full_column(self) -> None:
        """The routine itself is fine for a full column, verified vs MetPy."""
        if not V.metpy_available():
            pytest.skip("MetPy is not installed; no independent reference available")
        import warnings

        from metpy.calc import precipitable_water
        from metpy.units import units

        from app.ingestion.realtime.imdaa_netcdf import derive_iwv

        q = V.dewpoint_to_specific_humidity(self.FULL_P, self.FULL_TD)
        ours = float(np.asarray(derive_iwv(self.FULL_P, q)).squeeze())
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            reference = float(
                precipitable_water(self.FULL_P * units.hPa, self.FULL_TD * units.K).magnitude
            )
        assert ours == pytest.approx(reference, rel=0.01)

    def test_production_column_omits_a_measurable_share_of_the_total(self) -> None:
        """Quantifies *why* full-column IWV is not claimed: ~2 % is missing."""
        if not V.metpy_available():
            pytest.skip("MetPy is not installed")
        import warnings

        from metpy.calc import precipitable_water
        from metpy.units import units

        from app.ingestion.realtime.imdaa_netcdf import derive_iwv

        seven = slice(0, 7)  # the 1000-300 hPa levels the pipeline requests
        q_full = V.dewpoint_to_specific_humidity(self.FULL_P, self.FULL_TD)
        partial = float(np.asarray(derive_iwv(self.FULL_P[seven], q_full[seven])).squeeze())
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            reference = float(
                precipitable_water(self.FULL_P * units.hPa, self.FULL_TD * units.K).magnitude
            )
        omitted = (reference - partial) / reference
        assert 0.0 < omitted < 0.05, f"omitted fraction was {omitted:.4%}"
        # The documented estimate must match the measurement.
        assert V.iwv_scope()["unvalidated_fraction_estimate"] == pytest.approx(
            round(omitted, 2), abs=0.02
        )

    def test_scope_declares_partial_column_not_full_column(self) -> None:
        scope = V.iwv_scope()
        assert scope["is_full_column"] is False
        assert scope["surface_pressure_available"] is False
        assert scope["production_top_hpa"] == 300.0
        assert scope["full_column_top_hpa"] == 1.0
        assert "partial-column" in scope["quantity"]

    def test_scope_documents_its_blockers(self) -> None:
        blockers = " ".join(V.IWV_FULL_COLUMN_BLOCKERS)
        assert "300 hPa" in blockers
        assert "surface pressure" in blockers.lower()
        assert "No authentic full-column sounding" in blockers
        assert len(V.IWV_FULL_COLUMN_BLOCKERS) >= 3

    def test_iwv_report_carries_the_scope_warning(self) -> None:
        report = V.run_iwv_validation()
        assert any("NOT a full atmospheric column" in note for note in report.notes)


    def test_observational_evaluation_of_synthetic_cubes_writes_nothing(self, tmp_path) -> None:
        from app.training.evaluate import EvalConfig, evaluate

        target = tmp_path / "official-report.json"
        with pytest.raises(EvaluationBlocked):
            evaluate(
                EvalConfig(
                    mode=OBSERVATIONAL, n_events=1, split="test",
                    allow_untrained=True, is_synthetic=False,  # the old lying flag
                    output=str(target),
                )
            )
        assert not target.exists()
        assert not target.parent.exists() or not any(target.parent.iterdir())

    def test_eval_config_defaults_to_the_safe_mode(self) -> None:
        from app.training.evaluate import EvalConfig

        assert EvalConfig().mode == SYNTHETIC_EVAL
        assert EvalConfig().to_dict()["mode"] == SYNTHETIC_EVAL

    def test_observational_flag_is_a_hard_error(self) -> None:
        """Phase 8.3: the flag is rejected, not silently ignored.

        A deprecation warning would leave a harmful invocation working, so
        parsing fails loudly instead.
        """
        from app.training.evaluate import build_parser

        with pytest.raises(SystemExit) as excinfo:
            build_parser().parse_args(["--observational"])
        assert "removed in Phase 8.3" in str(excinfo.value)
        assert "--mode observational" in str(excinfo.value)

    def test_train_observational_flag_is_also_rejected(self) -> None:
        from app.training.train import build_parser

        with pytest.raises(SystemExit) as excinfo:
            build_parser().parse_args(["--observational"])
        assert "removed in Phase 8.3" in str(excinfo.value)

    def test_mode_still_parses_normally(self) -> None:
        from app.training.evaluate import build_parser as eval_parser
        from app.training.train import build_parser as train_parser

        assert eval_parser().parse_args(["--mode", "observational"]).mode == "observational"
        assert train_parser().parse_args(["--mode", "production"]).mode == "production"



# --------------------------------------------------------------------------- #
# Phase 8.3 - cryptographic provenance
# --------------------------------------------------------------------------- #
class TestHashVerification:
    def test_correct_hash_verifies(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256, verify_source_hash

        src = tmp_path / "s.bin"
        src.write_bytes(b"authentic bytes")
        result = verify_source_hash(file_sha256(src), src)
        assert result.status == "ok"
        assert result.verified is True
        assert result.expected == result.actual

    def test_tampered_file_is_rejected(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256, verify_source_hash

        src = tmp_path / "s.bin"
        src.write_bytes(b"authentic bytes")
        digest = file_sha256(src)
        src.write_bytes(b"tampered bytes!!")  # same length, different content
        result = verify_source_hash(digest, src)
        assert result.status == "mismatch"
        assert result.verified is False
        assert "modified since ingestion" in result.detail

    def test_missing_hash_is_never_a_pass(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import verify_source_hash

        src = tmp_path / "s.bin"
        src.write_bytes(b"bytes")
        result = verify_source_hash(None, src)
        assert result.status == "not_recorded"
        assert result.verified is False
        assert "never inferred from a filename" in result.detail

    def test_missing_file_is_distinct_from_a_mismatch(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import verify_source_hash

        result = verify_source_hash("0" * 64, tmp_path / "gone.bin")
        assert result.status == "bytes_unavailable"
        assert result.verified is False

    def test_digest_is_case_insensitive_but_exact(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256, verify_source_hash

        src = tmp_path / "s.bin"
        src.write_bytes(b"bytes")
        assert verify_source_hash(file_sha256(src).upper(), src).verified is True

    def test_hash_of_none_is_none(self) -> None:
        from app.ingestion.realtime.provenance import hash_file_or_none

        assert hash_file_or_none(None) is None
        assert hash_file_or_none("/nonexistent/path/x.bin") is None

    def test_verification_result_serialises(self) -> None:
        from app.ingestion.realtime.provenance import verify_source_hash

        payload = verify_source_hash(None, None).to_dict()
        assert payload["status"] == "not_recorded"
        assert payload["verified"] is False



class TestProvenanceSchemaIntegration:
    def test_provenance_round_trips_through_npz(self, tmp_path) -> None:
        from app.ingestion.base import ObservationCube
        from app.ingestion.realtime.provenance import file_sha256

        src = tmp_path / "s.bin"
        src.write_bytes(b"bytes")
        cube = _real_cube(
            synthetic=False, source_file=src, source_sha256=file_sha256(src)
        )
        reloaded = ObservationCube.load_npz(cube.save_npz(tmp_path / "c.npz"))
        record = reloaded.provenance[0]
        assert record.source_sha256 == file_sha256(src)
        assert record.source_path == str(src)
        assert record.source_bytes_available is True
        assert record.provider == "Test provider"
        assert record.channel_units
        assert record.coverage == "78-79E 29-30N"
        assert record.has_verifiable_hash is True

    def test_old_payload_without_integrity_fields_still_loads(self) -> None:
        """A Phase 8.2 record must load, defaulting to 'unknown' not 'verified'."""
        from app.ingestion.base import _provenance_from_dict

        old = {
            "source": "IMD", "product": "aws", "valid_from": "2019-07-01T00:00:00",
            "valid_to": None, "fetched_at": "2019-07-01T00:00:00",
            "path": "/x.geojson", "is_synthetic": False, "attribution": "IMD",
        }
        record = _provenance_from_dict(old)
        assert record.source_sha256 is None
        assert record.has_verifiable_hash is False

    def test_unknown_keys_are_dropped_not_fatal(self) -> None:
        from app.ingestion.base import _provenance_from_dict

        record = _provenance_from_dict({
            "source": "S", "product": "P", "valid_from": "2019-07-01T00:00:00",
            "some_future_field": 123,
        })
        assert record.source == "S"

    def test_tampered_source_blocks_observational_evaluation(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256

        src = tmp_path / "s.bin"
        src.write_bytes(b"authentic bytes")
        digest = file_sha256(src)
        cube = _real_cube(synthetic=False, source_file=src, source_sha256=digest)
        src.write_bytes(b"modified after ing")
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate([cube], requested_mode=OBSERVATIONAL)
        checks = {c["name"]: c for c in excinfo.value.report["checks"]}
        assert checks["source_hash_verified"]["passed"] is False
        assert "mismatch" in checks["source_hash_verified"]["detail"]

    def test_missing_hash_blocks_observational_evaluation(self) -> None:
        with pytest.raises(EvaluationBlocked) as excinfo:
            enforce_evaluation_gate(
                [_real_cube(synthetic=False)], requested_mode=OBSERVATIONAL
            )
        checks = {c["name"]: c for c in excinfo.value.report["checks"]}
        assert checks["source_hash_verified"]["passed"] is False
        # No manifest at all is *unknown*, and is reported as such rather than
        # being conflated with a recorded digest that failed.
        assert "unknown, not verified" in checks["source_hash_verified"]["detail"]

    def test_synthetic_demo_does_not_require_a_hash(self, tmp_path) -> None:
        """A synthetic run has no source file; that is reported, not failed."""
        report = enforce_evaluation_gate(
            [_real_cube(synthetic=True)],
            requested_mode=SYNTHETIC_EVAL,
            output=str(tmp_path / "synthetic-demo" / "r.json"),
        )
        checks = {c["name"]: c for c in report["checks"]}
        assert checks["source_hash_verified"]["passed"] is True
        assert "not applicable" in checks["source_hash_verified"]["detail"]

    def test_failed_verification_writes_no_observational_report(self, tmp_path) -> None:
        from app.training.evaluate import EvalConfig, evaluate

        target = tmp_path / "official.json"
        with pytest.raises(EvaluationBlocked):
            evaluate(
                EvalConfig(
                    mode=OBSERVATIONAL, n_events=1, split="test",
                    allow_untrained=True, output=str(target),
                )
            )
        assert not target.exists()

    def test_failed_verification_writes_no_checkpoint(self, tmp_path) -> None:
        from app.models.registry import CHECKPOINT_NAME
        from app.training.train import TrainConfig, train

        out = tmp_path / "model"
        with pytest.raises(TrainingBlocked):
            train(TrainConfig(n_events=1, epochs=1, max_steps=1, preset="lite",
                              output_dir=str(out), mode=PRODUCTION))
        assert not (out / CHECKPOINT_NAME).exists()



class TestProvenanceMigration:
    """Migration 0003 is additive, nullable and reversible."""

    NEW_COLUMNS = (
        "source_sha256", "source_bytes_available", "provider",
        "channel_units", "coverage", "acquired_at_src",
    )

    def _engine(self, tmp_path):
        from sqlalchemy import create_engine

        return create_engine(f"sqlite:///{tmp_path / 'db.sqlite'}")

    def _columns(self, engine) -> set[str]:
        from sqlalchemy import inspect

        return {c["name"] for c in inspect(engine).get_columns("dataset_provenance")}

    def test_migration_is_ordered_and_applied(self, tmp_path) -> None:
        from app.db.migrations import upgrade

        applied = upgrade(self._engine(tmp_path))
        assert applied == [
            "0001_initial_schema", "0002_dataset_provenance",
            "0003_provenance_integrity",
        ]

    def test_new_columns_are_added(self, tmp_path) -> None:
        from app.db.migrations import upgrade

        engine = self._engine(tmp_path)
        upgrade(engine)
        assert set(self.NEW_COLUMNS) <= self._columns(engine)

    def test_downgrade_then_re_upgrade_is_stable(self, tmp_path) -> None:
        from app.db.migrations import downgrade, upgrade

        engine = self._engine(tmp_path)
        upgrade(engine)
        assert downgrade(engine, to_revision="0002_dataset_provenance") == [
            "0003_provenance_integrity"
        ]
        assert not set(self.NEW_COLUMNS) <= self._columns(engine)
        assert upgrade(engine) == ["0003_provenance_integrity"]
        assert set(self.NEW_COLUMNS) <= self._columns(engine)

    def test_migration_is_idempotent(self, tmp_path) -> None:
        from app.db.migrations import upgrade

        engine = self._engine(tmp_path)
        upgrade(engine)
        assert upgrade(engine) == []   # nothing left to do

    def test_old_row_survives_and_reads_as_unknown(self, tmp_path) -> None:
        """A pre-0003 row keeps working and its integrity fields read NULL."""
        from datetime import datetime, timezone

        from sqlalchemy import text

        from app.db.migrations import current_revision, upgrade

        engine = self._engine(tmp_path)
        upgrade(engine, migrations=__import__(
            "app.db.migrations", fromlist=["MIGRATIONS"]
        ).MIGRATIONS[:2])
        assert current_revision(engine) == "0002_dataset_provenance"
        with engine.begin() as conn:
            conn.execute(text(
                "INSERT INTO dataset_provenance "
                "(ingest_key, source, product, data_class, acquired_at, ingested_at, "
                " path, checksum, crs, source_resolution, processed_resolution, "
                " source_cadence, processed_cadence, n_frames, detail, "
                " attribution, license_note) VALUES "
                "('k','IMD','aws','observation',:t,:t,'/x','', 'EPSG:4326','','','','',"
                " 1,'{}','IMD','')"
            ), {"t": datetime.now(tz=timezone.utc)})

        upgrade(engine)
        with engine.connect() as conn:
            row = conn.execute(text(
                "SELECT source_sha256, provider, coverage FROM dataset_provenance"
            )).fetchone()
        assert row[0] is None and row[1] is None and row[2] is None

    def test_orm_model_declares_the_columns(self) -> None:
        from app.db.models import DatasetProvenanceRow

        columns = {c.name for c in DatasetProvenanceRow.__table__.columns}
        assert set(self.NEW_COLUMNS) <= columns



class TestIngestionMetadata:
    """Real adapters must record units, coverage and a real digest."""

    def test_channel_units_are_declared_for_every_field(self) -> None:
        from app.ingestion.realtime.acquire import IMD_OGC_CHANNEL_UNITS

        assert IMD_OGC_CHANNEL_UNITS
        for field_name, unit in IMD_OGC_CHANNEL_UNITS.items():
            assert isinstance(field_name, str) and field_name
            assert isinstance(unit, str) and unit

    def test_digests_are_per_file_and_reproducible(self, tmp_path) -> None:
        from app.ingestion.realtime.acquire import _raw_digests
        from app.ingestion.realtime.provenance import file_sha256

        a, b = tmp_path / "a.geojson", tmp_path / "b.geojson"
        a.write_text('{"a":1}')
        b.write_text('{"b":2}')
        digests = _raw_digests([a, b])
        assert digests == {
            "a.geojson": file_sha256(a), "b.geojson": file_sha256(b)
        }
        # Stable across calls, and order-independent.
        assert _raw_digests([b, a]) == digests

    def test_unreadable_file_yields_no_digest_at_all(self, tmp_path) -> None:
        """No placeholder digest is invented for a file that cannot be read."""
        from app.ingestion.realtime.acquire import _raw_digests

        assert _raw_digests([tmp_path / "missing.geojson"]) == {}
        assert _raw_digests([]) == {}

    def test_modified_file_changes_its_digest(self, tmp_path) -> None:
        from app.ingestion.realtime.acquire import _raw_digests

        f = tmp_path / "a.geojson"
        f.write_text('{"a":1}')
        before = _raw_digests([f])["a.geojson"]
        f.write_text('{"a":2}')
        assert _raw_digests([f])["a.geojson"] != before

    def test_dataset_provenance_carries_the_new_fields(self) -> None:
        from datetime import datetime, timezone

        from app.ingestion.realtime.provenance import DataClass, DatasetProvenance

        record = DatasetProvenance(
            source="IMD GeoServer OGC", product="aws", data_class=DataClass.OBSERVATION,
            acquired_at=datetime.now(tz=timezone.utc),
            source_sha256="a" * 64, source_path="/x.geojson",
            source_bytes_available=True, provider="IMD",
            channel_units={"air_temperature": "degC"},
            coverage="77.5-80.5E 29.0-31.5N",
        )
        payload = record.to_dict()
        assert payload["source_sha256"] == "a" * 64
        assert payload["source_path"] == "/x.geojson"
        assert payload["provider"] == "IMD"
        assert payload["channel_units"] == {"air_temperature": "degC"}
        assert payload["coverage"] == "77.5-80.5E 29.0-31.5N"

    def test_generated_coverage_string_is_parseable(self) -> None:
        """The coverage the adapter writes must pass the parser it is checked by.

        Float formatting matters: `:g` renders 29.0 as "29", which produces a
        string the coverage parser rejects, silently un-verifying the dataset.
        """
        from app.ingestion.realtime.acquire import _coverage_string
        from app.training.gate import parse_coverage_string

        for bbox in [
            (77.5, 29.0, 80.5, 31.5),      # integers-as-floats in the middle
            (78.0, 29.0, 79.0, 30.0),
            (77.25, 28.75, 79.125, 30.5),
        ]:
            text = _coverage_string(bbox)
            assert parse_coverage_string(text) is not None, f"{bbox} -> {text!r}"

    def test_legacy_construction_still_works(self) -> None:
        """Every new field defaults, so Phase 6-8.2 call sites are unaffected."""
        from datetime import datetime, timezone

        from app.ingestion.realtime.provenance import DataClass, DatasetProvenance

        record = DatasetProvenance(
            source="S", product="P", data_class=DataClass.OBSERVATION,
            acquired_at=datetime.now(tz=timezone.utc),
        )
        assert record.source_sha256 is None
        assert record.source_path is None
        assert record.source_bytes_available is False
        assert record.channel_units == {}
        assert record.coverage is None
        assert record.to_dict()["source_sha256"] is None


# --------------------------------------------------------------------------- #
# Phase 8.4 - multi-file integrity, channel metadata, acquisition readiness
# --------------------------------------------------------------------------- #
class TestMultiFileIntegrity:
    def test_source_file_records_digest_and_size(self, tmp_path) -> None:
        from app.ingestion.base import source_file_from_disk
        from app.ingestion.realtime.provenance import file_sha256

        f = tmp_path / "a.nc"
        f.write_bytes(b"x" * 100)
        entry = source_file_from_disk(f, provider="NCMRWF", role="imdaa",
                                      source_identity="job-1")
        assert entry.sha256 == file_sha256(f)
        assert entry.size_bytes == 100
        assert entry.provider == "NCMRWF"
        assert entry.role == "imdaa"
        assert entry.source_identity == "job-1"
        assert entry.has_verifiable_hash is True

    def test_unreadable_file_yields_no_digest(self, tmp_path) -> None:
        from app.ingestion.base import source_file_from_disk

        entry = source_file_from_disk(tmp_path / "gone.nc")
        assert entry.sha256 is None
        assert entry.size_bytes is None
        assert entry.has_verifiable_hash is False

    def test_secondary_file_tampering_is_detected(self, tmp_path) -> None:
        """The whole point of the manifest: a tampered DEM must not slip through."""
        from app.ingestion.realtime.provenance import file_sha256

        primary = tmp_path / "primary.nc"
        dem = tmp_path / "dem.tif"
        primary.write_bytes(b"imdaa bytes")
        dem.write_bytes(b"dem bytes")
        cube = _real_cube(
            synthetic=False, source_file=primary, source_sha256=file_sha256(primary),
            extra_source_files=[dem],
        )
        dem.write_bytes(b"dem MODIFIED")  # only the secondary file
        checks = {c["name"]: c for c in verify_provenance([cube])}
        assert checks["source_hash_verified"]["passed"] is False
        assert "mismatch" in checks["source_hash_verified"]["detail"]

    def test_missing_secondary_file_is_detected(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256

        primary = tmp_path / "primary.nc"
        dem = tmp_path / "dem.tif"
        primary.write_bytes(b"a")
        dem.write_bytes(b"b")
        cube = _real_cube(
            synthetic=False, source_file=primary, source_sha256=file_sha256(primary),
            extra_source_files=[dem],
        )
        dem.unlink()
        checks = {c["name"]: c for c in verify_provenance([cube])}
        assert checks["source_hash_verified"]["passed"] is False

    def test_legacy_record_without_manifest_reads_as_unknown(self) -> None:
        """A pre-8.4 record has no manifest; it must not be reported verified."""
        from app.ingestion.base import _provenance_from_dict

        legacy = _provenance_from_dict({
            "source": "IMDAA", "product": "p", "valid_from": "2019-07-01T00:00:00",
            "fetched_at": "2019-07-01T00:00:00", "is_synthetic": False,
        })
        assert legacy.source_files == []
        assert legacy.has_verifiable_hash is False
        grid = GridSpec.from_bbox([78.0, 29.0, 79.0, 30.0], res_km=20.0)
        cube = ObservationCube(
            grid=grid,
            times=[BASE + dt.timedelta(minutes=30 * i) for i in range(6)],
            channels=np.ones((6, 12, *grid.shape), dtype=np.float32),
            provenance=[legacy],
        )
        checks = {c["name"]: c for c in verify_provenance([cube])}
        assert checks["source_hash_verified"]["passed"] is False
        assert "unknown, not verified" in checks["source_hash_verified"]["detail"]

    def test_dem_source_file_hashes_real_bytes(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256
        from app.ingestion.terrain import DEM_PROVIDER, dem_source_file

        dem_file = tmp_path / "srtm_uttarakhand.tif"
        dem_file.write_bytes(b"DEM elevation raster bytes 12345")
        entry = dem_source_file(dem_file)
        assert entry.path == str(dem_file)
        assert entry.sha256 == file_sha256(dem_file)
        assert entry.provider == DEM_PROVIDER
        assert entry.role == "dem"
        assert entry.source_identity == "srtm_uttarakhand"
        assert entry.bytes_available is True
        assert entry.has_verifiable_hash is True

    def test_dem_source_file_missing_path_fails_closed(self, tmp_path) -> None:
        from app.ingestion.terrain import dem_source_file

        missing = tmp_path / "non_existent.tif"
        entry = dem_source_file(missing)
        assert entry.sha256 is None
        assert entry.bytes_available is False
        assert entry.has_verifiable_hash is False

    def test_dem_provenance_and_gate_validation(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256
        from app.ingestion.terrain import DEMTile, dem_coverage_string, dem_provenance

        dem_file = tmp_path / "srtm_tile.tif"
        dem_file.write_bytes(b"geotiff dummy content 98765")
        tile = DEMTile(
            elevation_m=np.ones((10, 10), dtype=np.float32),
            min_lon=78.0,
            min_lat=29.0,
            max_lon=79.0,
            max_lat=30.0,
            source="SRTM",
            path=str(dem_file),
        )
        assert dem_coverage_string(tile) == "78.0-79.0E 29.0-30.0N"

        prov = dem_provenance(tile)
        assert prov.is_synthetic is False
        assert prov.channel_units == {"elevation": "m"}
        assert prov.source_sha256 == file_sha256(dem_file)
        assert len(prov.source_files) == 1
        assert prov.source_files[0].sha256 == file_sha256(dem_file)

        primary = tmp_path / "primary.nc"
        primary.write_bytes(b"primary observations")
        cube = _real_cube(
            synthetic=False,
            source_file=primary,
            source_sha256=file_sha256(primary),
            extra_source_files=[dem_file],
        )
        checks = {c["name"]: c for c in verify_provenance([cube])}
        assert checks["source_hash_verified"]["passed"] is True

        # Tampering DEM file fails closed
        dem_file.write_bytes(b"tampered DEM contents")
        tampered_checks = {c["name"]: c for c in verify_provenance([cube])}
        assert tampered_checks["source_hash_verified"]["passed"] is False
        assert "mismatch" in tampered_checks["source_hash_verified"]["detail"]

    def test_manifest_round_trips_through_npz(self, tmp_path) -> None:
        from app.ingestion.realtime.provenance import file_sha256

        primary = tmp_path / "primary.nc"
        primary.write_bytes(b"bytes")
        cube = _real_cube(
            synthetic=False, source_file=primary, source_sha256=file_sha256(primary),
            extra_source_files=[primary],
        )
        reloaded = ObservationCube.load_npz(cube.save_npz(tmp_path / "c.npz"))
        assert len(reloaded.provenance[0].source_files) == 1
        assert reloaded.provenance[0].source_files[0].sha256 == file_sha256(primary)




class TestModelChannelMetadata:
    def test_all_twelve_channels_have_complete_metadata(self) -> None:
        from app.physics import CHANNEL_META, CHANNELS

        assert len(CHANNEL_META) == len(CHANNELS) == 12
        assert {m.name for m in CHANNEL_META} == {s.name for s in CHANNELS}

    def test_units_and_ranges_match_channel_specs(self) -> None:
        from app.physics import CHANNEL_META_INDEX, CHANNELS

        for spec in CHANNELS:
            meta = CHANNEL_META_INDEX[spec.name]
            assert meta.unit == spec.unit, spec.name
            assert (meta.vmin, meta.vmax) == (spec.vmin, spec.vmax), spec.name

    def test_every_channel_states_nan_missing_semantics(self) -> None:
        from app.physics import CHANNEL_META

        for meta in CHANNEL_META:
            assert "NaN" in meta.missing, meta.name

    def test_station_units_never_leak_onto_satellite_channels(self) -> None:
        """An IMD station field's unit must not be attached to a radiance."""
        from app.ingestion.realtime.acquire import IMD_OGC_CHANNEL_UNITS
        from app.physics import CHANNEL_META_INDEX

        station_units = set(IMD_OGC_CHANNEL_UNITS.values())
        for name in ("tir1_bt", "tir2_bt", "wv_bt", "mir_bt", "ctt", "elevation"):
            assert CHANNEL_META_INDEX[name].unit not in station_units, name

    def test_each_channel_declares_its_own_source(self) -> None:
        from app.physics import CHANNEL_META_INDEX

        for name in ("tir1_bt", "tir2_bt", "wv_bt", "vis_refl", "swir_refl", "mir_bt"):
            assert "INSAT" in CHANNEL_META_INDEX[name].source, name
        assert "DEM" in CHANNEL_META_INDEX["elevation"].source
        assert "IMDAA" in CHANNEL_META_INDEX["cape"].source
        assert "IMDAA" in CHANNEL_META_INDEX["iwv"].source

    def test_channel_units_payload_covers_all_twelve(self) -> None:
        from app.physics import channel_units

        units = channel_units()
        assert len(units) == 12
        assert units["cape"] == "J kg-1"
        assert units["elevation"] == "m"
        assert units["iwv"] == "mm"

    def test_imdaa_units_only_cover_imdaa_channels(self) -> None:
        """IMDAA must not claim a unit for an INSAT or DEM channel."""
        from app.ingestion.realtime.imdaa_netcdf import IMDAA_DERIVED_CHANNELS

        assert set(IMDAA_DERIVED_CHANNELS) == {"cape", "iwv"}
        assert "tir1_bt" not in IMDAA_DERIVED_CHANNELS



class TestAcquisitionReadiness:
    def test_no_files_means_no_readiness(self, tmp_path) -> None:
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )

        report = assess_acquisition_readiness(data_dir=tmp_path, run_validation=False)
        assert report.files_acquired is False
        assert report.observational_readiness is False
        assert report.validation_status == {"cape": "not_run", "iwv": "not_run"}

    def test_real_files_get_digests_from_their_bytes(self, tmp_path) -> None:
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )
        from app.ingestion.realtime.provenance import file_sha256

        f = tmp_path / "imdaa.nc"
        f.write_bytes(b"real reanalysis bytes")
        report = assess_acquisition_readiness(source_files=[f], run_validation=False)
        stage = report.stage("files_acquired")
        assert stage.passed is True
        assert stage.evidence["files"][0]["sha256"] == file_sha256(f)

    def test_missing_credential_is_reported_not_assumed(self, monkeypatch) -> None:
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )

        for name in ("SIHPS_RDS_EMAIL", "SIHPS_RDS_PASSWORD",
                     "SIHPS_MOSDAC_USER", "SIHPS_MOSDAC_PASSWORD"):
            monkeypatch.delenv(name, raising=False)
        report = assess_acquisition_readiness(run_validation=False)
        evidence = report.stage("source_access").evidence
        assert evidence["ncmrwf-rds"]["credentials_present"] is False
        assert set(evidence["ncmrwf-rds"]["missing_env"]) == {
            "SIHPS_RDS_EMAIL", "SIHPS_RDS_PASSWORD"
        }

    def test_insat_channels_stay_missing_without_credentials(self, monkeypatch) -> None:
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )

        for name in ("SIHPS_MOSDAC_USER", "SIHPS_MOSDAC_PASSWORD"):
            monkeypatch.delenv(name, raising=False)
        report = assess_acquisition_readiness(run_validation=False)
        assert "tir1_bt" in report.channels_missing
        assert "elevation" not in report.channels_missing  # DEM needs no credential
        assert report.observational_readiness is False

    def test_readiness_is_never_asserted_even_when_validation_passes(self) -> None:
        """CAPE/IWV passing is necessary but never sufficient."""
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )

        report = assess_acquisition_readiness()
        assert report.validation_status["cape"] == "pass"
        assert report.observational_readiness is False
        assert report.stage("observational_readiness").passed is False

    def test_report_lists_blockers_and_actions(self) -> None:
        from app.ingestion.realtime.acquisition_readiness import (
            assess_acquisition_readiness,
        )

        report = assess_acquisition_readiness(run_validation=False)
        assert report.blockers and report.next_actions
        assert set(report.to_dict()) >= {
            "observational_readiness", "source_access", "files_acquired",
            "data_processed", "stages", "channels_missing", "next_actions",
        }

    def test_cli_flag_is_registered(self) -> None:
        from app.ingestion.realtime.imdaa_acquire import build_parser

        assert build_parser().parse_args(["--acquisition-readiness"]).acquisition_readiness
