"""Synthetic but physically-structured demo data generator.

The prototype must be runnable with **zero credentials**, so this module
synthesises:

* a fractal Himalayan-style DEM with carved drainage valleys (SRTM substitute),
* INSAT-3D-like radiances (TIR1/TIR2/WV/VIS/SWIR/MIR) for advecting convective
  systems, including overshooting tops and orographic enhancement,
* IMDAA-like atmospheric columns (T/p/q/u/v) whose parcel ascent produces
  realistic CAPE/CIN,
* labels (thunderstorm, rainfall class, cloudburst, flash flood) computed from
  the *same physics* that drives the imagery plus terrain exposure, so the
  learning problem is well posed.

Everything is seeded and reproducible; the data is explicitly flagged
``is_synthetic=True`` in the provenance and is never presented as an observation.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Sequence

import numpy as np

from app.grid import FRAME_MINUTES, GridSpec, km_per_deg_lat, km_per_deg_lon
from app.ingestion.base import (
    DataConnector,
    ObservationCube,
    Provenance,
    TerrainStack,
    WindowSpec,
    parse_time,
    utcnow,
)
from app.logging_conf import get_logger
from app.nputils import box_smooth, gaussian_smooth, local_extreme
from app.physics import (
    CHANNELS,
    N_CHANNELS,
    channel_index,
    cooling_rate,
    moisture_flux_convergence,
    rain_class_from_rate,
    rain_rate_from_ctt,
    water_vapour_anomaly,
)

logger = get_logger("ingestion.synthetic")

SYNTHETIC_ATTRIBUTION = (
    "Synthetic demo field generated by SIHPS (not a satellite or reanalysis observation). "
    "Real deployments read INSAT-3D/3DR Level-2 from MOSDAC and IMDAA reanalysis."
)


# --------------------------------------------------------------------------- #
# Event catalogue
# --------------------------------------------------------------------------- #
@dataclass(slots=True)
class EventSpec:
    """Description of one synthetic weather event."""

    event_id: str
    kind: str                      # quiet | thunderstorm | cloudburst | flash_flood
    region: str
    district: str
    state: str
    init_time: datetime
    seed: int
    n_cells: int = 2
    peak_intensity: float = 0.75
    steering_u: float = 6.0        # m s-1 (eastward)
    steering_v: float = 3.0        # m s-1 (northward)
    moisture_plume: float = 1.0    # multiplier on the column-moisture anomaly
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["init_time"] = self.init_time.isoformat()
        payload["documented_source"] = "Synthetic catalogue entry (mirrors IMD/NDMA cloudburst case studies)"
        return payload


def default_event_catalog(year: int = 2024) -> list[EventSpec]:
    """A small catalogue mirroring the event types used for validation."""
    base = datetime(year, 7, 15, 3, 0, tzinfo=timezone.utc)
    entries = [
        ("evt-quiet-001", "quiet", "Dehradun", "Dehradun", "Uttarakhand", 11, 0, 0.05, "Weak pre-monsoon day"),
        ("evt-thunder-001", "thunderstorm", "Haridwar", "Haridwar", "Uttarakhand", 21, 2, 0.78, "Afternoon thunderstorm line"),
        ("evt-cloudburst-001", "cloudburst", "Uttarkashi", "Uttarkashi", "Uttarakhand", 31, 3, 0.94, "Orographic cloudburst, valley head"),
        ("evt-cloudburst-002", "cloudburst", "Chamoli", "Chamoli", "Uttarakhand", 41, 3, 0.90, "Cloudburst over steep catchment"),
        ("evt-flood-001", "flash_flood", "Rishikesh", "Pauri Garhwal", "Uttarakhand", 51, 2, 0.86, "Flash flood, Ganga/Alaknanda plains"),
        ("evt-flood-002", "flash_flood", "Rudraprayag", "Rudraprayag", "Uttarakhand", 61, 2, 0.82, "Flash flood after 3 h accumulation"),
    ]
    specs: list[EventSpec] = []
    for idx, (eid, kind, region, district, state, seed, cells, peak, note) in enumerate(entries):
        specs.append(
            EventSpec(
                event_id=eid,
                kind=kind,
                region=region,
                district=district,
                state=state,
                init_time=base + timedelta(days=idx * 9, hours=idx % 5),
                seed=seed,
                n_cells=cells,
                peak_intensity=peak,
                steering_u=float(4 + (seed % 5)),
                steering_v=float(1 + (seed % 3)),
                moisture_plume=0.55 if kind == "quiet" else 1.0 + 0.15 * (seed % 3),
                notes=note,
            )
        )
    return specs


# --------------------------------------------------------------------------- #
# DEM synthesis
# --------------------------------------------------------------------------- #
def generate_dem(
    grid: GridSpec,
    *,
    seed: int = 7,
    valley_count: int = 2,
    base_elev_m: float = 320.0,
    relief_m: float = 4600.0,
) -> np.ndarray:
    """Fractal Himalayan-style DEM with carved north-south drainage valleys.

    The result is *not* real topography, but it reproduces the two properties the
    flood head needs: a strong elevation gradient and convergent valleys with
    high flow accumulation.
    """
    rng = np.random.RandomState(seed)
    ny, nx = grid.shape
    yy, xx = np.meshgrid(np.linspace(0.0, 1.0, ny), np.linspace(0.0, 1.0, nx), indexing="ij")

    # Large-scale orographic trend: high in the north-east, low in the south-west.
    trend = 0.10 + 0.80 * (0.60 * yy + 0.40 * (1.0 - xx))

    # Fractal (multi-octave sinusoidal) roughness with a steep spectral falloff,
    # which keeps the surface self-affine but free of excessive local pits.
    frac = np.zeros_like(trend)
    for octave in range(1, 8):
        amp = 1.0 / (octave**2.0)
        theta = rng.uniform(0.0, 2.0 * np.pi)
        phase = rng.uniform(0.0, 2.0 * np.pi)
        freq = 1.1 * octave
        frac += amp * np.sin(2.0 * np.pi * freq * (np.cos(theta) * xx + np.sin(theta) * yy) + phase)
    frac /= np.abs(frac).max() + 1e-9

    elevation = base_elev_m + relief_m * np.clip(trend + 0.16 * frac, 0.0, 1.25)

    # Carve meandering valleys from north to south to create convergent flow.
    for _ in range(valley_count):
        x0 = rng.uniform(0.18, 0.82)
        amplitude = rng.uniform(0.04, 0.10)
        frequency = rng.uniform(0.8, 1.6)
        phase = rng.uniform(0.0, 2.0 * np.pi)
        width = rng.uniform(0.025, 0.055)
        centre = x0 + amplitude * np.sin(2.0 * np.pi * frequency * yy + phase)
        depth = rng.uniform(700.0, 1400.0)
        elevation -= depth * np.exp(-(((xx - centre) / width) ** 2))
        # Two tributaries per valley => dendritic drainage network.
        for _ in range(2):
            y0 = rng.uniform(0.2, 0.8)
            slope = rng.uniform(0.3, 0.7)
            tributary = y0 + slope * (xx - x0)
            elevation -= 0.45 * depth * np.exp(-(((yy - tributary) / (width * 1.4)) ** 2))

    return np.maximum(elevation, 60.0)


# --------------------------------------------------------------------------- #
# Atmosphere synthesis
# --------------------------------------------------------------------------- #
@dataclass(slots=True)
class SyntheticConfig:
    """Knobs for the synthetic atmosphere (sensor realism + window geometry)."""

    n_frames: int = 18
    dt_hours: float = 0.5
    sensor_noise_k: float = 0.35
    missing_block_prob: float = 0.015
    block_size: int = 6
    steering_scale: float = 0.35  # keep systems inside the AOI for a 9 h sequence


class SyntheticAtmosphere:
    """Generates one physically-structured event sequence on the model grid."""

    def __init__(
        self,
        grid: GridSpec,
        terrain: TerrainStack,
        spec: EventSpec,
        config: SyntheticConfig | None = None,
    ) -> None:
        self.grid = grid
        self.terrain = terrain
        self.spec = spec
        self.config = config or SyntheticConfig()
        self.rng = np.random.RandomState(spec.seed)
        self.ny, self.nx = grid.shape
        self.dt_hours = self.config.dt_hours
        self.dx_m = grid.d_lon * km_per_deg_lon(0.5 * (grid.min_lat + grid.max_lat)) * 1000.0
        self.dy_m = grid.d_lat * km_per_deg_lat() * 1000.0
        self.yy, self.xx = np.meshgrid(np.arange(self.ny), np.arange(self.nx), indexing="ij")
        self.elevation = np.asarray(terrain.elevation_m, dtype=np.float64)
        self.slope_norm = np.clip(np.asarray(terrain.slope_deg, dtype=np.float64) / 40.0, 0.0, 1.0)
        self.flow_norm = terrain.normalised_flow
        self.diurnal = self._diurnal_cycle()
        self.cells = self._storm_track()

    # ------------------------------------------------------------- internals
    def _diurnal_cycle(self) -> np.ndarray:
        """Skin-temperature diurnal amplitude factor per frame (peaks ~14:30 IST)."""
        hours_utc = np.array(
            [
                (self.spec.init_time + timedelta(hours=self.dt_hours * i)).hour
                + (self.spec.init_time.minute / 60.0)
                for i in range(self.config.n_frames)
            ]
        )
        local_hour = (hours_utc + 5.5) % 24.0
        return np.sin(2.0 * np.pi * (local_hour - 9.0) / 24.0)  # -1 at 09 IST, +1 at 21 IST

    def _storm_track(self) -> list[dict[str, Any]]:
        """Cells with advection, growth and orographic anchoring.

        Convective cells are anchored on high-slope cell heads (where slope is
        large and flow accumulation moderate) and drift with the scaled steering
        wind, matching observed orographic cloudburst behaviour.
        """
        track: list[dict[str, Any]] = []
        if self.spec.n_cells <= 0:
            return track
        # Candidate genesis points: steep slopes, moderate flow accumulation.
        candidate = np.argsort(-(self.slope_norm + 0.4 * self.flow_norm).ravel())
        for index, flat in enumerate(candidate[: self.spec.n_cells * 60 : 20][: self.spec.n_cells]):
            row, col = divmod(int(flat), self.nx)
            u_cells = self.spec.steering_u * self.config.steering_scale * self.dt_hours * 3600.0 / self.dx_m
            v_cells = self.spec.steering_v * self.config.steering_scale * self.dt_hours * 3600.0 / self.dy_m
            peak_frame = float(self.config.n_frames) * (0.45 + 0.08 * index)
            width = {"quiet": 0.0, "thunderstorm": 0.30, "cloudburst": 0.16, "flash_flood": 0.34}.get(
                self.spec.kind, 0.25
            ) * self.config.n_frames
            track.append(
                {
                    "row0": float(row) - 0.35 * self.config.n_frames * v_cells,
                    "col0": float(col) - 0.35 * self.config.n_frames * u_cells,
                    "u_cells": float(u_cells),
                    "v_cells": float(v_cells),
                    "radius": float(self.rng.uniform(5.0, 9.0)),
                    "growth": float(self.rng.uniform(0.03, 0.08)),
                    "peak": float(self.spec.peak_intensity * self.rng.uniform(0.9, 1.05)),
                    "peak_frame": peak_frame,
                    "width": max(width, 1.0),
                }
            )
        return track

    def cell_intensity(self, frame_index: int) -> np.ndarray:
        """Per-cell 2-D intensity field (``0..1``) at a frame, with orographic boost."""
        field = np.zeros(self.grid.shape, dtype=np.float64)
        for cell in self.cells:
            row = cell["row0"] + cell["v_cells"] * frame_index
            col = cell["col0"] + cell["u_cells"] * frame_index
            radius = cell["radius"] * (1.0 + cell["growth"] * frame_index)
            pulse = np.exp(-0.5 * ((frame_index - cell["peak_frame"]) / cell["width"]) ** 2)
            amplitude = cell["peak"] * pulse
            if amplitude <= 1e-3:
                continue
            dist2 = ((self.yy - row) ** 2 + (self.xx - col) ** 2) / max(radius**2, 1e-6)
            core = np.exp(-dist2)
            core *= 1.0 + 0.55 * self.slope_norm  # orographic enhancement
            field = np.maximum(field, amplitude * np.clip(core, 0.0, 1.35))
        return np.clip(field, 0.0, 1.0)

    def _moisture_fields(self, frame_index: int, intensity: np.ndarray) -> dict[str, np.ndarray]:
        """Low-level wind, moisture and instability fields for one frame."""
        plume = self.spec.moisture_plume
        lead = np.clip(intensity, 0.0, 1.0)
        # Subsidence (dry slot) surrounding the convective core.
        dry_slot = np.clip(1.0 - 2.2 * gaussian_smooth(lead, sigma=6.0), 0.0, 1.0)
        iwv = (
            24.0
            + 10.0 * self.flow_norm
            + 26.0 * plume * gaussian_smooth(lead, sigma=3.0)
            - 9.0 * dry_slot
            + 1.5 * self.rng.randn(*self.grid.shape)
        )
        iwv = np.clip(gaussian_smooth(iwv, sigma=1.2), 3.0, 68.0)

        q850 = np.clip(iwv / 1000.0, 0.001, 0.024)  # column moisture proxy
        shear = 1.0 + 0.8 * self.flow_norm
        u850 = self.spec.steering_u * shear + 3.0 * gaussian_smooth(lead, 4.0)
        v850 = self.spec.steering_v * shear + 20.0 * np.gradient(gaussian_smooth(lead, 5.0), axis=1)
        mfc = moisture_flux_convergence(u850, v850, q850, self.dx_m / 1000.0, self.dy_m / 1000.0)
        mfc_pos = np.clip(mfc, 0.0, None)
        mfc_norm = mfc_pos / (np.percentile(mfc_pos, 99.0) + 1e-9)

        cape = (
            500.0
            + 2400.0 * mfc_norm
            + 900.0 * np.clip(plume - 0.6, 0.0, None)
            + 260.0 * self.diurnal[frame_index]
            + 60.0 * self.rng.randn(*self.grid.shape)
        )
        cape = np.clip(gaussian_smooth(cape, sigma=1.5), 0.0, 4900.0)
        cin = np.clip(320.0 - 0.12 * cape + 25.0 * self.rng.randn(*self.grid.shape), 0.0, 400.0)
        t2m = 300.0 - 0.0062 * self.elevation + 5.5 * self.diurnal[frame_index]
        sp_hpa = 1013.0 * np.exp(-self.elevation / 8400.0)
        return {
            "iwv": iwv,
            "q850": q850,
            "u850": u850,
            "v850": v850,
            "mfc": mfc,
            "cape": cape,
            "cin": cin,
            "t2m": t2m,
            "sp_hpa": sp_hpa,
            "dry_slot": dry_slot,
        }

    def _radiance_frame(self, frame_index: int, intensity: np.ndarray) -> dict[str, np.ndarray]:
        """Synthesise the six INSAT-like channels plus derived features for one frame."""
        noise = self.config.sensor_noise_k
        moisture = self._moisture_fields(frame_index, intensity)
        t_skin = 300.0 - 0.0062 * self.elevation + 6.0 * self.diurnal[frame_index]

        cloud_fraction = np.clip(1.05 * intensity, 0.0, 1.0)
        ctt = t_skin - intensity * (t_skin - 195.0)
        overshoot = np.clip((intensity - 0.90) / 0.10, 0.0, 1.0)  # overshooting tops
        ctt = ctt - 4.0 * overshoot
        ctt = np.clip(ctt + 0.25 * self.rng.randn(*self.grid.shape), 185.0, 320.0)

        cirrus = np.clip(0.75 * gaussian_smooth(np.clip(intensity, 0.0, 1.0), sigma=4.0), 0.0, 1.0)
        tir1 = ctt + noise * self.rng.randn(*self.grid.shape)
        tir2 = tir1 + 0.6 + 3.2 * cirrus + 0.2 * self.rng.randn(*self.grid.shape)
        wv = 252.0 - 5.0 * np.clip(moisture["iwv"] - 24.0, -20.0, 30.0) + 13.0 * moisture["dry_slot"]
        wv = wv - 16.0 * intensity + 0.4 * self.rng.randn(*self.grid.shape)

        snow = np.clip((self.elevation - 3200.0) / 1200.0, 0.0, 1.0)
        vis = 0.05 + 0.68 * cloud_fraction + 0.28 * snow * (1.0 - cloud_fraction)
        vis = np.clip(vis + 0.02 * self.rng.randn(*self.grid.shape), 0.0, 1.0)
        swir = np.clip(
            0.04 + 0.30 * cloud_fraction + 0.18 * cirrus + 0.015 * self.rng.randn(*self.grid.shape), 0.0, 1.0
        )
        solar = np.clip(0.4 + 0.6 * np.maximum(self.diurnal[frame_index], 0.0), 0.0, 1.0)
        mir = tir1 + 20.0 + 16.0 * cloud_fraction * solar + 0.5 * self.rng.randn(*self.grid.shape)

        return {
            "tir1_bt": tir1,
            "tir2_bt": tir2,
            "wv_bt": wv,
            "vis_refl": vis,
            "swir_refl": swir,
            "mir_bt": np.clip(mir, 250.0, 350.0),
            "ctt": np.clip(ctt - 0.5 - 0.8 * cirrus, 180.0, 300.0),
            "_intensity": intensity,
            "_cloud_fraction": cloud_fraction,
            "_diagnostics": moisture,
        }

    # --------------------------------------------------- missing data handling
    def _inject_missing(self, frames: Sequence[dict[str, np.ndarray]]) -> np.ndarray:
        """Drop random blocks in the sensor channels; return a quality stack.

        Mirrors real INSAT-3D Level-2 gaps (scan-sector dropouts, transmission
        loss) so that the temporal-interpolation path is exercised on every run.
        """
        n_frames = len(frames)
        quality = np.ones((n_frames, *self.grid.shape), dtype=np.float32)
        sensor_channels = ("tir1_bt", "tir2_bt", "wv_bt", "vis_refl", "swir_refl", "mir_bt")
        block = self.config.block_size
        for index, frame in enumerate(frames):
            n_blocks = self.rng.poisson(self.config.missing_block_prob * 40)
            for _ in range(int(n_blocks)):
                row = self.rng.randint(0, max(1, self.ny - block))
                col = self.rng.randint(0, max(1, self.nx - block))
                for name in sensor_channels:
                    frame[name][row : row + block, col : col + block] = np.nan
                quality[index, row : row + block, col : col + block] = 0.0
        return quality

    @staticmethod
    def _temporal_fill(stack: np.ndarray) -> np.ndarray:
        """Fill NaNs along the time axis with the nearest valid value.

        Forward fill, then backward fill, then spatial Gaussian inpainting for
        pixels that were missing in every frame.
        """
        filled = stack.copy()
        for t in range(1, filled.shape[0]):
            nan = ~np.isfinite(filled[t])
            filled[t][nan] = filled[t - 1][nan]
        for t in range(filled.shape[0] - 2, -1, -1):
            nan = ~np.isfinite(filled[t])
            if nan.any():
                filled[t][nan] = filled[t + 1][nan]
        for t in range(filled.shape[0]):
            nan = ~np.isfinite(filled[t])
            if nan.any():
                smoothed = gaussian_smooth(np.nan_to_num(filled[t], nan=float(np.nanmean(filled[t]))), 2.0)
                filled[t][nan] = smoothed[nan]
        return filled

    # -------------------------------------------------------------- labelling
    def _build_labels(
        self,
        channels: np.ndarray,
        diagnostics: Sequence[dict[str, np.ndarray]],
        exposure: np.ndarray | None = None,
    ) -> dict[str, np.ndarray]:
        """Derive thunderstorm / rainfall-class / cloudburst / flood targets.

        The targets are computed from the *physical* fields (cloud-top
        temperature, column moisture, rainfall-rate proxy and terrain exposure),
        which is why a model can learn them from the same imagery.
        """
        n_frames = channels.shape[0]
        ctt = channels[:, channel_index("ctt"), :, :]
        iwv = channels[:, channel_index("iwv"), :, :]
        intensity = np.stack([frame["_intensity"] for frame in diagnostics])
        convective = np.clip(
            1.0 + 0.8 * intensity + 0.4 * self.slope_norm[None, :, :], 0.0, 2.2
        )
        rain_rate = rain_rate_from_ctt(ctt, iwv) * convective
        thunderstorm = ((ctt <= 233.0) & (rain_rate >= 3.0)).astype(np.float32)
        rain_class = rain_class_from_rate(rain_rate).astype(np.int8)
        cloudburst = ((rain_rate >= 35.0) & (iwv >= 34.0)).astype(np.float32)

        # 3-hour rainfall accumulation with exponential decay (runoff memory).
        accumulation = np.zeros_like(rain_rate)
        acc = np.zeros(self.grid.shape, dtype=np.float64)
        decay = np.exp(-self.dt_hours / 2.5)
        for t in range(n_frames):
            acc = acc * decay + rain_rate[t] * self.dt_hours
            accumulation[t] = acc

        if exposure is None:
            exposure = self.slope_norm  # degraded fallback (no terrain exposure)
        runoff_index = accumulation * (0.35 + 0.65 * exposure)
        flood_soft = np.clip(runoff_index / 45.0, 0.0, 1.0).astype(np.float32)
        flood = (flood_soft >= 0.5).astype(np.float32)
        return {
            "thunderstorm": thunderstorm,
            "rain_class": rain_class,
            "cloudburst": cloudburst,
            "flood": flood,
            "flood_soft": flood_soft,
            "rain_rate_mmh": rain_rate.astype(np.float32),
            "rain_accumulation_mm": accumulation.astype(np.float32),
        }

    # ------------------------------------------------------------------ build
    def sounding_profile(self) -> dict[str, list[float]]:
        """A plausible representative vertical profile for the Weather Intelligence page.

        Generated from the surface state with a standard lapse rate, a moist
        boundary layer and speed shear; for display/demonstration only.
        """
        levels = [1000.0, 925.0, 850.0, 700.0, 600.0, 500.0, 400.0, 300.0, 200.0]
        surface_c = 300.0 - 0.0062 * float(np.median(self.elevation)) - 273.15
        temp_c = [surface_c - 6.5 * (1000.0 - p) / 1000.0 * 0.65 for p in levels]
        dewpoint_c = [t - (3.0 + 0.25 * i) for i, t in enumerate(temp_c)]
        u = [self.spec.steering_u * (0.6 + 0.12 * i) for i in range(len(levels))]
        v = [self.spec.steering_v * (0.7 + 0.10 * i) for i in range(len(levels))]
        return {
            "pressure_hpa": levels,
            "temperature_c": [round(t, 2) for t in temp_c],
            "dewpoint_c": [round(t, 2) for t in dewpoint_c],
            "u_wind_ms": [round(x, 2) for x in u],
            "v_wind_ms": [round(x, 2) for x in v],
        }

    def imd_station_observations(self, channels: np.ndarray, n_stations: int = 24) -> list[dict[str, Any]]:
        """Synthetic IMD-style ground station reports (rainfall, T, RH)."""
        from app.physics import dewpoint_kelvin, relative_humidity_percent

        rng = np.random.RandomState(self.spec.seed + 991)
        stations: list[dict[str, Any]] = []
        rows = rng.randint(1, self.ny - 1, size=n_stations)
        cols = rng.randint(1, self.nx - 1, size=n_stations)
        ctt = channels[:, channel_index("ctt")]
        iwv = channels[:, channel_index("iwv")]
        for index, (row, col) in enumerate(zip(rows, cols)):
            lat, lon = self.grid.cell_center(int(row), int(col))
            cold = float(np.mean(np.clip(280.0 - ctt[:, row, col], 0.0, 80.0)) * 0.35)
            column = float(np.mean(iwv[:, row, col]))
            t_k = 300.0 - 0.0062 * float(self.elevation[row, col])
            q = max(column / 1000.0, 1e-4)
            stations.append(
                {
                    "station_id": f"IMD-SYN-{index:03d}",
                    "name": f"Synthetic station {index:03d}",
                    "lat": round(lat, 4),
                    "lon": round(lon, 4),
                    "elevation_m": round(float(self.elevation[row, col]), 1),
                    "rainfall_mm": round(cold, 2),
                    "temperature_c": round(t_k - 273.15, 2),
                    "dewpoint_c": round(float(dewpoint_kelvin(900.0, q)) - 273.15, 2),
                    "relative_humidity_pct": round(float(relative_humidity_percent(900.0, t_k, q)), 1),
                    "source": "IMD (synthetic replica)",
                    "is_synthetic": True,
                }
            )
        return stations

    def build(self, *, exposure: np.ndarray | None = None) -> tuple[ObservationCube, dict[str, Any]]:
        """Synthesise the full sequence and return ``(cube, diagnostics)``.

        Steps: radiance frames -> sensor gaps -> temporal inpainting -> derived
        features (CTT cooling rate, WV anomaly) -> physical labels.
        """
        n_frames = self.config.n_frames
        frames = [self._radiance_frame(t, self.cell_intensity(t)) for t in range(n_frames)]
        quality = self._inject_missing(frames)

        stack = np.zeros((n_frames, N_CHANNELS, *self.grid.shape), dtype=np.float64)
        for name in ("tir1_bt", "tir2_bt", "wv_bt", "vis_refl", "swir_refl", "mir_bt", "ctt"):
            stack[:, channel_index(name)] = self._temporal_fill(np.stack([frame[name] for frame in frames]))

        ctt_series = stack[:, channel_index("ctt")]
        stack[:, channel_index("ctt_cooling_rate")] = cooling_rate(ctt_series, self.dt_hours)

        wv_series = stack[:, channel_index("wv_bt")]
        background = gaussian_smooth(np.median(wv_series, axis=0), sigma=8.0)
        stack[:, channel_index("wv_bt_anomaly")] = np.stack(
            [water_vapour_anomaly(frame, background) for frame in wv_series]
        )

        diagnostics = {
            key: np.stack([frame["_diagnostics"][key] for frame in frames]).astype(np.float32)
            for key in ("iwv", "q850", "u850", "v850", "mfc", "cape", "cin", "t2m", "sp_hpa", "dry_slot")
        }
        # Instability-index diagnostics (proxies derived from the column state).
        from app.physics import dewpoint_kelvin, k_index, total_totals_index

        t850 = diagnostics["t2m"] - 1.0
        t700 = diagnostics["t2m"] - 12.0
        t500 = diagnostics["t2m"] - 30.0
        td850 = np.array([dewpoint_kelvin(850.0, q) for q in diagnostics["q850"]]) - 273.15
        diagnostics["ki"] = k_index(t850, td850 + 273.15, t700, td850 + 273.15 - 6.0, t500).astype(np.float32)
        diagnostics["tt"] = total_totals_index(t850, td850 + 273.15, t500).astype(np.float32)
        diagnostics["li"] = (8.0 - diagnostics["cape"] / 320.0).astype(np.float32)

        stack[:, channel_index("iwv")] = diagnostics["iwv"]
        stack[:, channel_index("cape")] = diagnostics["cape"]
        stack[:, channel_index("elevation")] = self.elevation[None, :, :]

        labels = self._build_labels(stack, frames, exposure=exposure)
        times = [self.spec.init_time + timedelta(minutes=FRAME_MINUTES * i) for i in range(n_frames)]
        cube = ObservationCube(
            grid=self.grid,
            times=times,
            channels=stack.astype(np.float32),
            quality=quality,
            provenance=[
                Provenance(
                    source="INSAT-3D/3DR (synthetic replica)",
                    product="L2B TIR1/TIR2/WV/VIS/SWIR/MIR + derived CTT",
                    valid_from=times[0],
                    valid_to=times[-1],
                    is_synthetic=True,
                    attribution=SYNTHETIC_ATTRIBUTION,
                ),
                Provenance(
                    source="IMDAA (synthetic replica)",
                    product="0.12 deg 3-hourly reanalysis diagnostics",
                    valid_from=times[0],
                    valid_to=times[-1],
                    is_synthetic=True,
                    attribution=SYNTHETIC_ATTRIBUTION,
                ),
            ],
            labels=labels,
            metadata={
                "event": self.spec.to_dict(),
                "grid_summary": {"shape": list(self.grid.shape), "resolution_km": self.grid.res_km},
                "sounding": self.sounding_profile(),
                "frame_diagnostics": {
                    "max_cape_j_kg": [float(x) for x in diagnostics["cape"].max(axis=(1, 2))],
                    "mean_iwv_mm": [float(x) for x in diagnostics["iwv"].mean(axis=(1, 2))],
                    "min_ctt_k": [float(x) for x in ctt_series.min(axis=(1, 2))],
                },
                "imd_stations": self.imd_station_observations(stack, n_stations=24),
            },
        )
        return cube, diagnostics


# --------------------------------------------------------------------------- #
# Terrain persistence helpers (used by build_demo_terrain and the API cache)
# --------------------------------------------------------------------------- #
def save_terrain_stack(stack: Any, path: str | Path) -> Path:
    """Persist a terrain stack (npz + embedded grid/provenance JSON)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        elevation_m=stack.elevation_m.astype(np.float32),
        slope_deg=stack.slope_deg.astype(np.float32),
        aspect_deg=stack.aspect_deg.astype(np.float32),
        flow_accumulation=stack.flow_accumulation.astype(np.float32),
        drainage_basin=stack.drainage_basin.astype(np.int32),
        twi=stack.twi.astype(np.float32),
        land_use=stack.land_use.astype(np.int8),
        grid=np.array(json.dumps(stack.grid.to_dict())),
        provenance=np.array(json.dumps(stack.provenance.to_dict() if stack.provenance else {})),
    )
    return path


def load_terrain_stack(path: str | Path) -> Any:
    """Load a terrain stack written by :func:`save_terrain_stack`."""
    from app.ingestion.base import TerrainStack

    with np.load(Path(path), allow_pickle=False) as data:
        grid = GridSpec.from_dict(json.loads(str(data["grid"])))
        payload = json.loads(str(data["provenance"])) or None
        provenance = None
        if payload:
            provenance = Provenance(
                **{
                    **payload,
                    "valid_from": parse_time(payload["valid_from"]),
                    "valid_to": None,
                    "fetched_at": parse_time(payload["fetched_at"]),
                }
            )
        return TerrainStack(
            grid=grid,
            elevation_m=data["elevation_m"].astype(np.float64),
            slope_deg=data["slope_deg"].astype(np.float64),
            aspect_deg=data["aspect_deg"].astype(np.float64),
            flow_accumulation=data["flow_accumulation"].astype(np.float64),
            drainage_basin=data["drainage_basin"].astype(np.int64),
            twi=data["twi"].astype(np.float64),
            land_use=data["land_use"].astype(np.int64),
            provenance=provenance,
        )


def build_demo_terrain(
    grid: GridSpec, *, seed: int = 7, cache_path: Path | None = None
) -> tuple[Any, np.ndarray]:
    """Build (or load) the demo terrain stack and its exposure score.

    Returns ``(terrain_stack, exposure_score)``; used across the API, Celery
    tasks and training so every component sees identical terrain.
    """
    from app.ingestion.terrain import DEMTile, TerrainProcessor

    processor = TerrainProcessor(grid, demo_mode=True)
    if cache_path is not None and Path(cache_path).exists():
        try:
            stack = load_terrain_stack(cache_path)
            return stack, processor.exposure_score(stack)
        except (OSError, ValueError, KeyError) as exc:  # corrupt cache -> rebuild
            logger.warning("terrain cache unusable, rebuilding", extra={"error": str(exc)})
    dem = DEMTile(
        elevation_m=generate_dem(grid, seed=seed),
        min_lon=grid.min_lon,
        min_lat=grid.min_lat,
        max_lon=grid.max_lon,
        max_lat=grid.max_lat,
        source="SIHPS synthetic DEM (SRTM stand-in)",
    )
    stack = processor.build(dem)
    if cache_path is not None:
        save_terrain_stack(stack, cache_path)
    return stack, processor.exposure_score(stack)


class SyntheticINSATConnector(DataConnector):
    """INSAT-3D/3DR stand-in connector for demo mode (MOSDAC-compatible shape)."""

    source_name = "INSAT-3D/3DR (synthetic)"
    is_synthetic = True

    def __init__(self, grid: GridSpec, terrain: Any, *, config: SyntheticConfig | None = None) -> None:
        super().__init__(grid, demo_mode=True)
        self.terrain = terrain
        self.config = config or SyntheticConfig()
        self.last_diagnostics: dict[str, Any] | None = None
        self.last_atmosphere: SyntheticAtmosphere | None = None

    def fetch(self, spec: EventSpec | None = None, *, exposure: np.ndarray | None = None) -> ObservationCube:
        """Generate one synthetic sequence (``spec`` defaults to the cloudburst case)."""
        spec = spec or default_event_catalog()[2]
        atmosphere = SyntheticAtmosphere(self.grid, self.terrain, spec, self.config)
        cube, diagnostics = atmosphere.build(exposure=exposure)
        self.last_diagnostics = diagnostics
        self.last_atmosphere = atmosphere
        return cube

    def health(self) -> dict[str, Any]:
        payload = super().health()
        payload["channels"] = [spec.name for spec in CHANNELS]
        payload["attribution"] = SYNTHETIC_ATTRIBUTION
        return payload


class SyntheticIMDAAConnector(DataConnector):
    """IMDAA reanalysis stand-in: pressure-level diagnostics on the model grid."""

    source_name = "IMDAA (synthetic)"
    is_synthetic = True

    def __init__(self, grid: GridSpec, terrain: Any, *, config: SyntheticConfig | None = None) -> None:
        super().__init__(grid, demo_mode=True)
        self.terrain = terrain
        self.config = config or SyntheticConfig()

    def fetch(
        self, spec: EventSpec | None = None, *, exposure: np.ndarray | None = None
    ) -> tuple[dict[str, Any], ObservationCube]:
        """Return ``(diagnostics, cube)`` for the requested event."""
        spec = spec or default_event_catalog()[2]
        atmosphere = SyntheticAtmosphere(self.grid, self.terrain, spec, self.config)
        cube, diagnostics = atmosphere.build(exposure=exposure)
        diagnostics["sounding"] = atmosphere.sounding_profile()
        diagnostics["levels_hpa"] = [1000.0, 925.0, 850.0, 700.0, 600.0, 500.0, 400.0, 300.0, 200.0]
        return diagnostics, cube


class SyntheticIMDConnector(DataConnector):
    """IMD ground-observation stand-in (validation / reference station reports)."""

    source_name = "IMD (synthetic)"
    is_synthetic = True

    def fetch(self, cube: ObservationCube, *, n_stations: int = 24) -> list[dict[str, Any]]:
        """Station reports consistent with the supplied cube."""
        return list(cube.metadata.get("imd_stations", []))[:n_stations]


# --------------------------------------------------------------------------- #
# Dataset materialisation
# --------------------------------------------------------------------------- #
def materialise_event(
    out_dir: str | Path,
    grid: GridSpec,
    spec: EventSpec,
    *,
    terrain: Any | None = None,
    config: SyntheticConfig | None = None,
) -> dict[str, Any]:
    """Write one event sequence (``.npz``) to disk and return its manifest entry."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if terrain is None:
        terrain, _ = build_demo_terrain(grid, cache_path=out_dir / "terrain_stack.npz")
    from app.ingestion.terrain import TerrainProcessor

    exposure = TerrainProcessor(grid, demo_mode=True).exposure_score(terrain)
    atmosphere = SyntheticAtmosphere(grid, terrain, spec, config)
    cube, diagnostics = atmosphere.build(exposure=exposure)
    path = cube.save_npz(out_dir / "sequences" / f"{spec.event_id}.npz")
    return {
        **spec.to_dict(),
        "path": str(path),
        "n_frames": cube.n_frames,
        "times": [t.isoformat() for t in cube.times],
        "label_positive_fraction": {
            key: float(np.mean(value)) for key, value in cube.labels.items() if value.dtype != np.int8
        },
        "diagnostics_summary": {
            "max_cape_j_kg": float(diagnostics["cape"].max()),
            "max_iwv_mm": float(diagnostics["iwv"].max()),
            "max_rain_rate_mmh": float(cube.labels["rain_rate_mmh"].max()),
        },
    }


def generate_demo_dataset(
    out_dir: str | Path,
    grid: GridSpec,
    *,
    specs: Sequence[EventSpec] | None = None,
    config: SyntheticConfig | None = None,
    seed: int = 7,
) -> dict[str, Any]:
    """Generate the complete demo dataset: terrain, sequences, catalogue, stations."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    event_specs = list(specs or default_event_catalog())
    terrain, exposure = build_demo_terrain(grid, seed=seed, cache_path=out_dir / "terrain_stack.npz")
    save_terrain_stack(terrain, out_dir / "terrain_stack.npz")
    np.save(out_dir / "exposure.npy", exposure.astype(np.float32))

    manifest = [materialise_event(out_dir, grid, spec, terrain=terrain, config=config) for spec in event_specs]
    catalogue = {
        "generated_at": utcnow().isoformat(),
        "disclaimer": SYNTHETIC_ATTRIBUTION,
        "grid": grid.to_dict(),
        "n_events": len(manifest),
        "events": manifest,
        "terrain": terrain.to_dict(),
    }
    (out_dir / "catalogue.json").write_text(json.dumps(catalogue, indent=2), encoding="utf-8")

    stations = ObservationCube.load_npz(manifest[0]["path"]).metadata.get("imd_stations", []) if manifest else []
    (out_dir / "imd_stations.json").write_text(
        json.dumps({"stations": stations, "disclaimer": SYNTHETIC_ATTRIBUTION}, indent=2), encoding="utf-8"
    )
    logger.info("demo dataset generated", extra={"out_dir": str(out_dir), "n_events": len(manifest)})
    return catalogue


def load_demo_cube(out_dir: str | Path, event_id: str) -> ObservationCube:
    """Load a generated demo sequence by event id."""
    return ObservationCube.load_npz(Path(out_dir) / "sequences" / f"{event_id}.npz")


def list_demo_events(out_dir: str | Path) -> list[dict[str, Any]]:
    """Read the demo catalogue event list (``[]`` when not yet generated)."""
    path = Path(out_dir) / "catalogue.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8")).get("events", [])
