/** Tests for the formatting, risk-scale and provenance helpers. */

import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'

import type { DataSourcesHealth, GridInfo, Provenance } from '../api/types'
import { EXPERIMENTAL_DISCLAIMER } from '../api/types'
import { DataSourcePanel, ProvenanceBanner, SyntheticFlag, bannerTone } from '../components/Provenance'
import {
  DEFAULT_THRESHOLDS,
  categorise,
  formatJson,
  formatLeadHours,
  formatPercent,
  formatProbability,
  formatRelative,
  formatTimestamp,
  gridCentre,
  shortenId,
} from '../lib/format'

const GRID: GridInfo = {
  min_lon: 77.5,
  min_lat: 29.0,
  max_lon: 80.5,
  max_lat: 31.5,
  nx: 144,
  ny: 139,
  res_km: 2.0,
  effective_res_km: { x: 2.0, y: 2.0 },
  crs: 'EPSG:4326',
  frame_minutes: 30,
}

describe('categorise', () => {
  it('uses the backend thresholds when supplied', () => {
    expect(categorise(0.1)).toBe('LOW')
    expect(categorise(0.3)).toBe('MODERATE')
    expect(categorise(0.6)).toBe('HIGH')
    expect(categorise(0.85)).toBe('EXTREME')
  })

  it('respects custom thresholds', () => {
    expect(categorise(0.4, [0.2, 0.3, 0.9])).toBe('HIGH')
  })

  it('falls back to the documented defaults', () => {
    expect(DEFAULT_THRESHOLDS).toEqual([0.3, 0.6, 0.85])
  })
})

describe('formatters', () => {
  it('formats probabilities without inventing a value', () => {
    expect(formatProbability(0.839347)).toBe('0.839')
    expect(formatProbability(null)).toBe('—')
    expect(formatProbability(undefined)).toBe('—')
    expect(formatProbability(Number.NaN)).toBe('—')
  })

  it('formats percentages', () => {
    expect(formatPercent(0.5214)).toBe('52%')
    expect(formatPercent(0.5214, 1)).toBe('52.1%')
  })

  it('formats lead times in minutes below an hour', () => {
    expect(formatLeadHours(0.5)).toBe('30 min')
    expect(formatLeadHours(3)).toBe('3 h')
    expect(formatLeadHours(1.5)).toBe('1.5 h')
  })

  it('tolerates an unparsable timestamp', () => {
    expect(formatTimestamp('not-a-date')).toBe('not-a-date')
    expect(formatTimestamp(null)).toBe('—')
    expect(formatTimestamp('2024-08-02T13:30:00+00:00')).toContain('2024-08-02')
  })

  it('formats relative ages', () => {
    const now = Date.parse('2024-08-02T13:30:00Z')
    expect(formatRelative('2024-08-02T13:29:30Z', now)).toBe('30s ago')
    expect(formatRelative('2024-08-02T13:20:00Z', now)).toBe('10 min ago')
    expect(formatRelative('2024-08-02T11:30:00Z', now)).toBe('2 h ago')
  })

  it('shortens long identifiers but keeps both ends', () => {
    const digest = '5bbad210167873c8aabbccddeeff0011'
    const short = shortenId(digest, 8, 6)
    // First `head` and last `tail` characters are preserved around an ellipsis.
    expect(short).toBe(`5bbad210…${digest.slice(-6)}`)
    expect(short.length).toBeLessThan(digest.length)
  })

  it('leaves short strings alone', () => {
    expect(shortenId('abc')).toBe('abc')
    expect(shortenId(null)).toBe('—')
  })

  it('serialises structures for the provenance panel', () => {
    expect(formatJson({ a: 1 })).toContain('"a": 1')
  })
})

describe('gridCentre', () => {
  it('returns the midpoint of the AOI', () => {
    expect(gridCentre(GRID)).toEqual({ lat: 30.25, lon: 79.0 })
  })
})

describe('bannerTone', () => {
  it('defaults to synthetic when provenance is missing', () => {
    expect(bannerTone(null)).toBe('synthetic')
    expect(bannerTone(undefined)).toBe('synthetic')
  })

  it('reports synthetic for demo mode even if is_synthetic is false', () => {
    // Fail safe: an inconsistent payload must not read as operational.
    expect(bannerTone({ is_synthetic: false, demo_mode: true })).toBe('synthetic')
  })

  it('reports synthetic when the flag is set', () => {
    expect(bannerTone({ is_synthetic: true, demo_mode: false })).toBe('synthetic')
  })

  it('reports operational only when both flags are clearly false', () => {
    expect(bannerTone({ is_synthetic: false, demo_mode: false })).toBe('operational')
  })
})

describe('ProvenanceBanner', () => {
  const SYNTHETIC: Provenance = {
    demo_mode: true,
    is_synthetic: true,
    data_source: 'SIHPS synthetic demo generator (not an observation)',
    attribution: 'Synthetic demo field generated by SIHPS',
    disclaimer: 'This is NOT an official India Meteorological Department (IMD) warning.',
    accuracy_claim: 'No independent observational validation and no forecasting skill claim.',
  }

  const OPERATIONAL: Provenance = {
    ...SYNTHETIC,
    demo_mode: false,
    is_synthetic: false,
    data_source: 'Operational feed',
  }

  it('shows the synthetic label and the backend disclaimer text', () => {
    render(<ProvenanceBanner provenance={SYNTHETIC} />)

    expect(screen.getByText('SYNTHETIC DEMONSTRATION')).toBeInTheDocument()
    // Verbatim, not paraphrased: the caveat must not be softened.
    expect(screen.getByText(SYNTHETIC.disclaimer)).toBeInTheDocument()
    expect(screen.getByText(/No independent observational validation/)).toBeInTheDocument()
    expect(screen.getByText(SYNTHETIC.data_source)).toBeInTheDocument()
  })

  it('switches to an operational label when the backend says it is not synthetic', () => {
    render(<ProvenanceBanner provenance={OPERATIONAL} />)
    expect(screen.getByText('OPERATIONAL')).toBeInTheDocument()
  })

  it('hides the detail block in compact mode but keeps the flag', () => {
    render(<ProvenanceBanner provenance={SYNTHETIC} compact />)
    expect(screen.getByText('SYNTHETIC DEMONSTRATION')).toBeInTheDocument()
    expect(screen.queryByText(SYNTHETIC.disclaimer)).not.toBeInTheDocument()
  })
})

describe('SyntheticFlag', () => {
  it('labels a synthetic payload', () => {
    render(<SyntheticFlag isSynthetic />)
    expect(screen.getByText('SYNTHETIC')).toBeInTheDocument()
  })

  it('labels a non-synthetic payload', () => {
    render(<SyntheticFlag isSynthetic={false} />)
    expect(screen.getByText('OPERATIONAL')).toBeInTheDocument()
  })
})


/* -------------------------------------------------------------------------- */
/* Real-data transparency (Phase 5)                                           */
/* -------------------------------------------------------------------------- */

function dataSources(overrides: Partial<DataSourcesHealth> = {}): DataSourcesHealth {
  return {
    any_real_available: false,
    sources: [
      {
        source: 'MOSDAC INSAT-3D/3DR',
        availability: 'needs_credentials',
        available: false,
        is_synthetic: false,
        reason: 'MOSDAC downloads require an approved account',
        manual_instructions: 'Register at https://mosdac.gov.in/signup/',
      },
    ],
    split_feasibility: {
      requested: { train: [2015, 2022], val: [2023, 2023], test: [2024, 2025] },
      available: { 'hourly-pressure': [1979, 2020] },
      feasible: false,
      unsatisfiable: ['train'],
      proposed: { train: [2008, 2014], val: [2015, 2017], test: [2018, 2020] },
      notes: ['The required 2024-2025 test window is covered ONLY by MERA'],
    },
    ...overrides,
  }
}

describe('DataSourcePanel', () => {
  it('states plainly that no real feed is connected', () => {
    render(<DataSourcePanel dataSources={dataSources()} disclaimer={EXPERIMENTAL_DISCLAIMER} />)
    expect(screen.getByText(/synthetic demonstration data/i)).toBeTruthy()
  })

  it('never claims a blocked source is connected', () => {
    render(<DataSourcePanel dataSources={dataSources()} disclaimer={EXPERIMENTAL_DISCLAIMER} />)
    expect(screen.getByText('NEEDS ACCOUNT')).toBeTruthy()
    expect(screen.queryByText('CONNECTED')).toBeNull()
  })

  it('surfaces the historical coverage shortfall', () => {
    render(<DataSourcePanel dataSources={dataSources()} disclaimer={EXPERIMENTAL_DISCLAIMER} />)
    expect(screen.getByText(/cannot be built from currently accessible data/i)).toBeTruthy()
    expect(screen.getByText(/covered ONLY by MERA/)).toBeTruthy()
  })

  it('always renders the experimental disclaimer', () => {
    render(<DataSourcePanel dataSources={dataSources()} disclaimer={EXPERIMENTAL_DISCLAIMER} />)
    expect(screen.getByText(/NOT an official India Meteorological Department/i)).toBeTruthy()
  })

  it('renders nothing when the backend reports no data_sources block', () => {
    const { container } = render(
      <DataSourcePanel dataSources={null} disclaimer={EXPERIMENTAL_DISCLAIMER} />,
    )
    expect(container.innerHTML).toBe('')
  })

  it('shows CONNECTED only when the backend says available', () => {
    render(
      <DataSourcePanel
        dataSources={dataSources({
          any_real_available: true,
          sources: [
            {
              source: 'IMDAA/MERA (NCMRWF RDS)',
              availability: 'available',
              available: true,
              is_synthetic: false,
              reason: '12 local file(s) present',
            },
          ],
        })}
        disclaimer={EXPERIMENTAL_DISCLAIMER}
      />,
    )
    expect(screen.getByText('CONNECTED')).toBeTruthy()
  })
})

describe('EXPERIMENTAL_DISCLAIMER', () => {
  it('matches the backend wording exactly', () => {
    // Mirrors app/ingestion/base.py; drift here is a compliance bug.
    expect(EXPERIMENTAL_DISCLAIMER).toBe(
      'Experimental AI prediction for research and preparedness support only. ' +
        'This is NOT an official India Meteorological Department (IMD) warning. ' +
        'Always refer to IMD for authoritative alerts.',
    )
  })
})

